import { createContext, useCallback, useContext, useEffect, useMemo, useState } from 'react';

const UiContext = createContext(null);

const dictionaries = {
  zh: {
    nav: {
      dashboard: '总览',
      accounts: '账号登录',
      lotteries: '任务编排',
      strategy: '策略决策',
      knowledge: '经验知识',
      experiments: '实验',
      riskIntel: '风险情报',
      learning: '学习',
      governance: '治理',
      transitions: '迁移图谱',
      tasks: '实时流',
      events: '事件时间线',
      risk: '安全风控',
      deploy: '运维通知',
    },
    common: {
      local: '本机运行',
      language: '语言',
      theme: '主题',
      light: '浅色',
      dark: '深色',
      system: '跟随系统',
      refresh: '刷新',
      delete: '删除',
      cancel: '取消',
    },
    accounts: {
      eyebrow: '账号访问',
      title: '登录控制中心',
      healthRecheck: '健康复查',
      qrLogin: '二维码登录',
      qrBroker: '扫码登录代理',
      platform: '平台',
      generateQr: '生成二维码',
      qrOpening: '正在打开平台登录页并截取二维码画面...',
      qrEmpty: '选择平台后生成二维码登录会话，然后使用官方 App 扫码。',
      qrOfficialAlt: 'Bilibili 官方登录二维码',
      qrOfficialHint: '请使用哔哩哔哩官方 App 扫码并在手机上确认。',
      cookieLogin: 'Cookie 登录',
      cookieImport: '导入原始 Cookie 或 JSON Cookie',
      cookie: 'Cookie',
      cookiePlaceholder: '直接粘贴 Cookie 请求头，例如：SESSDATA=...; bili_jct=...; DedeUserID=...',
      importCreate: '导入并创建',
      accountPool: '账号池',
      refreshCredentials: '刷新已有账号凭据',
      noAccounts: '暂无账号',
      noRefresh: '请先创建账号，再刷新凭据。',
      imported: '已导入',
      missing: '缺失',
      notChecked: '未检查',
      evidence: '证据',
      noRisk: '暂无近期风险',
      accountCreated: '账号已创建',
      importQueued: '账号已创建并进入校准队列',
      credentialSaved: 'Cookie 已保存并进入校准队列',
      statusUpdated: '账号状态已更新',
      calibrationQueued: '账号校准已排队',
      healthDone: '账号健康复查完成',
      deleteConfirm: '确认删除该账号及关联记录？此操作不可撤销。',
      deleted: '账号已删除',
      rawCookieHint: '支持直接粘贴浏览器 Cookie 请求头、多行 Cookie 或 JSON Cookie 导出。',
      runtime: '运行状态',
    },
    dashboard: {
      eyebrow: '运行时',
      title: '运维总览',
      workersOnline: '在线 Worker',
      pendingTasks: '待处理任务',
      readyAccounts: '可用账号',
      coolingAccounts: '冷却账号',
      todayExecutions: '今日执行',
      memory: '内存',
      dryRunPlatforms: 'Dry-run 平台',
      realRunPlatforms: 'Real-run 平台',
      safeAccounts: '安全账号',
      notifyChannels: '通知通道',
      proxyExits: '代理出口',
      risk24h: '24 小时风险',
      nextActions: '下一步动作',
      noActions: '当前无需修复动作',
      strategyAdvice: '复盘与策略建议',
      strategyWindow: '基于最近 {days} 天执行、风险、目标池与通知状态生成。',
      noStrategyAdvice: '当前暂无策略建议',
      productionReady: '生产就绪',
      productionGate: '生产门禁',
      blocked: '阻塞',
      platformReadiness: '平台就绪度',
      platform: '平台',
      dryRun: 'Dry run',
      realRun: 'Real run',
      probe: '探针',
      blockers: '阻塞项',
      noProbe: '无探针',
      clear: '通过',
      loading: '正在加载就绪度数据',
      kickerLogin: '登录',
      kickerSafety: '安全',
      kickerNotify: '通知',
      loginTitle: '二维码 + Cookie 会话',
      loginText: '账号只有在存在有效加密凭据后才会进入账号池。',
      safetyTitle: '频率窗口 + 每日上限',
      safetyText: 'Worker 会阻止不安全执行，并将风险账号移入冷却或需登录状态。',
      notifyTitle: 'ServerChan / 飞书 / Webhook / Telegram',
      notifyText: '每次分发都会记录日志，避免通知失败被静默隐藏。',
      blockersMap: {
        'adapter probe is incomplete': '适配器探针不完整',
        'no calibrated ready account': '没有已校准可用账号',
        'real adapter not enabled': '真实动作适配器未启用',
        'global real-run switch is disabled': '全局 real-run 开关关闭',
        adapter_probe_incomplete: '适配器探针不完整',
        no_calibrated_ready_account: '没有已校准可用账号',
        real_adapter_not_enabled: '真实动作适配器未启用',
        global_real_run_disabled: '全局 real-run 开关关闭',
      },
      actionsMap: {
        configureNotificationTitle: '配置至少一个通知通道',
        configureNotificationDetail: '设置 ServerChan、飞书、Webhook 或 Telegram 密钥后，发送一次通知测试。',
        reviewRiskTitle: '复查近期账号风险信号',
        reviewRiskDetail: '进入安全风控页查看最新风险事件，必要时重新校准受影响账号。',
        addProxyTitle: '为生产账号添加隔离代理出口',
        addProxyDetail: '为每个生产账号绑定可用代理出口，并让高风险出口保持冷却。',
        addAccountTitle: '为 {platform} 添加已校准安全账号',
        addAccountDetail: '使用二维码或 Cookie 导入账号，然后运行账号校准，使 dry-run 可以安全自动选号。',
        completeProbeTitle: '完成 {platform} 适配器探针',
        completeProbeDetail: '用低风险账号运行探针，确认关注、点赞、评论、转发四个阶段可见。',
        enableAdapterTitle: '启用 {platform} 真实动作适配器',
        enableAdapterDetail: '基于探针证据配置选择器，真实执行前必须覆盖四个阶段。',
        dryRunOnlyTitle: '生产派发保持 dry-run 模式',
        dryRunOnlyDetail: '可以继续 dry-run 验证；真实执行必须等账号、探针、适配器和门禁全部满足。',
      },
      checksMap: {
        worker_onlineTitle: '至少一个 Worker 在线',
        worker_onlineDetail: '必须能看到 Worker 消费者或数据库心跳，否则任务不会执行。',
        real_run_global_switchTitle: '全局 real-run 开关受控',
        real_run_global_switchDetail: '真实执行默认关闭，只有完成生产确认后才应打开。',
        notification_readyTitle: '至少一个通知通道可用',
        notification_readyDetail: '生产告警需要 ServerChan、飞书、Webhook 或 Telegram。',
        target_pool_readyTitle: '存在可派发抽奖目标',
        target_pool_readyDetail: '目标池至少需要一个 pending 或 claimed 状态的目标。',
        all_platforms_dry_readyTitle: '所有平台具备 dry-run 账号',
        all_platforms_dry_readyDetail: '多平台 dry-run 需要每个平台至少一个已校准账号。',
        real_run_availableTitle: '至少一个平台可真实执行',
        real_run_availableDetail: '真实执行需要账号、探针证据、适配器和全局门禁同时满足。',
        active_proxy_exitTitle: '存在可用代理出口',
        active_proxy_exitDetail: '账号隔离需要至少一个未冷却的 active 代理出口。',
        safe_accounts_proxiedTitle: '可用账号已分配代理',
        safe_accounts_proxiedDetail: '生产账号应绑定可用代理出口，降低账号关联风险。',
        recent_risk_clearTitle: '24 小时内无账号风险',
        recent_risk_clearDetail: '近期风险事件需要复核，必要时重新校准账号。',
      },
      strategyMap: {
        configure_notificationsTitle: '先配置通知再进入自主运行',
        configure_notificationsDetail: '当前没有外部通知通道，中奖、失败、验证码或封禁可能只留在日志中。',
        run_shadow_before_realTitle: '真实执行前先跑 shadow-run',
        run_shadow_before_realDetail: '目标池已有待处理目标，但最近 7 天没有成功 shadow-run 记录。',
        promote_dry_to_shadowTitle: '将 dry-run 验证推进到 shadow-run',
        promote_dry_to_shadowDetail: 'dry-run 已经成功，下一步应在无副作用模式下打开真实页面验证登录态和风险信号。',
        complete_real_gateTitle: '基于 shadow 证据完成 real-run 门禁',
        complete_real_gateDetail: '已有 shadow-run 证据，但当前没有平台满足真实执行就绪条件。',
        review_failed_runsTitle: '放量前复查失败执行',
        review_failed_runsDetail: '近期任务失败需要结合证据截图和事件时间线复盘，再扩大调度规模。',
        cooldown_risky_accountsTitle: '冷却并重新校准风险账号',
        cooldown_risky_accountsDetail: '近期存在风险事件，建议冷却受影响账号、重新校准，或绑定更安全代理出口。',
        prioritize_high_value_targetsTitle: '优先处理高价值待派发目标',
        prioritize_high_value_targetsDetail: '存在高评分待处理目标且有安全账号可用，shadow-run 通过后应优先按预期价值派发。',
        recover_stale_tasksTitle: '恢复超时活跃任务',
        recover_stale_tasksDetail: '发现超过 30 分钟仍处于 queued/running 的任务，需要检查 Worker 健康和恢复守护逻辑。',
        continue_controlled_real_runTitle: '保持受控 real-run 节奏',
        continue_controlled_real_runDetail: '近期真实执行成功，策略复盘未发现紧急阻塞项。',
      },
      units: {
        nodes: '节点',
        items: '项',
        accounts: '账号',
        runs: '次',
        configured: '已配置',
        calibrated: '已校准',
        events: '事件',
        of: '/',
      },
    },
    lotteries: {
      eyebrow: '工作流',
      title: '任务编排',
      autoPick: '自动选择已校准账号',
      calibrated: '已校准',
      strategyQueue: '策略队列',
      strategyQueueHint: '根据目标价值、账号就绪、dry/shadow 证据、风险和失败记录排序。',
      rank: '排名',
      priorityScore: '策略分',
      expectedValue: '期望值',
      recommendedMode: '建议模式',
      recommendedAccount: '推荐账号',
      knowledge: '经验',
      reasons: '原因',
      dispatchRecommended: '按建议派发',
      noStrategyTargets: '暂无可排程目标',
      dryRun: 'Dry run',
      shadowRun: 'Shadow run',
      real: 'Real',
      dry_run: 'Dry run',
      shadow_run: 'Shadow run',
      real_run: 'Real',
      blocked: '阻塞',
      qrLogin: '二维码登录',
      cookieLogin: 'Cookie 登录',
      realActions: '真实动作',
      adapter: '适配器',
      safeAccounts: '安全账号',
      phases: '阶段',
      adapterLoading: '正在加载适配器诊断',
      cookieDomain: 'Cookie 域名',
      manualIntake: '手动活动录入',
      platform: '平台',
      activityUrl: '活动 URL',
      score: '评分',
      create: '创建',
      discoverySources: '发现源',
      type: '类型',
      interval: '间隔',
      sourceValue: '源内容',
      sourceValuePlaceholder: 'URL 列表或发现条件',
      upUidPlaceholder: '输入 Bilibili UP 主数字 UID',
      saveSource: '保存源',
      scanNow: '立即扫描',
      sourceSaved: '发现源已保存',
      scanComplete: '扫描完成：新增 {inserted}，发现 {found}，失败 {failed}',
      activityCreated: '活动已创建',
      defaultPlatform: '默认平台',
      defaultScore: '默认评分',
      uploadTargets: '上传目标',
      targetList: '目标列表',
      targetPlaceholder: '每行一个 URL，或使用 platform,url,score,expires_at\nhttps://www.bilibili.com/video/BV...\nbilibili,https://t.bilibili.com/123456789,80,2026-06-30 23:59:59',
      importTargets: '导入目标',
      targetsImported: '目标导入完成：新增 {created_count}，重复 {duplicate_count}，无效 {invalid_count}',
      targetFileLoaded: '已读取目标文件：{name}',
      importSummary: '已处理 {received} 行，新增 {created_count}，重复 {duplicate_count}，无效 {invalid_count}',
      dispatchQueued: '任务已派发',
      probeQueued: '适配器探针已排队',
      resultUpdated: '结果已更新',
      activityPool: '活动池',
      url: 'URL',
      rulePlan: '规则计划',
      ruleReady: '规则已确认',
      ruleNeedsReview: '规则待确认',
      ruleTextPlaceholder: '活动规则原文',
      confirmRule: '确认动作计划',
      ruleSaved: '活动动作计划已保存',
      suggestRule: '建议动作计划',
      suggesting: '建议生成中…',
      suggestionConfidence: '建议置信度：{value}%',
      suggestionAmbiguous: '规则文本含模糊表述，请人工核实',
      suggestionUnsupportedPrefix: '需人工处理：',
      actions: {
        followed: '关注',
        liked: '点赞',
        commented: '评论',
        reposted: '转发',
      },
      unsupportedActions: {
        mention_friends: '@好友（需人工艾特）',
        favorited: '收藏（需人工收藏）',
      },
      status: '状态',
      expires: '过期时间',
      action: '操作',
      noSafeAccount: '无安全账号',
      adapterPending: '适配器待配置',
      dispatchReal: '派发真实任务',
      dispatchDry: '派发 Dry',
      dispatch_dry_run: '派发 Dry',
      dispatch_shadow_run: '派发 Shadow',
      dispatch_real_run: '派发真实任务',
      won: '中奖',
      lost: '未中',
      probe: '探针',
      noActivities: '暂无活动',
      noSources: '暂无发现源',
      adapterProbes: '适配器探针',
      account: '账号',
      activity: '活动',
      visiblePhases: '可见阶段',
      quality: '质量',
      evidence: '证据',
      raw: '原始',
      openProbe: '打开探针',
      noAdapterProbes: '暂无适配器探针',
      executionRuns: '执行记录',
      task: '任务',
      mode: '模式',
      openEvidence: '打开证据',
      noRuns: '暂无执行记录',
      lastScan: '上次扫描',
      active: '启用',
      realAdapterMissing: '该平台真实动作适配器尚未可用。',
      realGate: 'Real 门禁',
      gateReady: '可真实执行',
      gateBlocked: '证据不足',
      gateUnknown: '未计算',
      nextActions: {
        add_target: '先添加真实活动',
        review_rule: '先确认活动规则',
        add_account: '先添加账号',
        configure_adapter: '先配置适配器',
        probe: '先跑探针',
        shadow_run: '先跑 Shadow',
        review_risk: '先复查风险',
        enable_real_run: '先开启总开关',
        blocked: '门禁阻断',
        real_run: '派发真实任务',
      },
      nextActionHints: {
        add_target: '请先添加 Bilibili 视频或动态活动链接，首页和测试 URL 不能用于探针或执行。',
        review_rule: '请展开活动池中的规则计划，核对规则原文并确认所需动作。',
        add_account: '请先到账号登录页添加并校准 Bilibili 账号。',
        configure_adapter: '请先到运维通知页，根据完整探针保存适配器选择器。',
        review_risk: '请先到安全风控页复查账号近期风险。',
        enable_real_run: '全局 real-run 开关需要管理员在运维页确认开启。',
        blocked: 'Real-run 门禁尚未满足。',
      },
      realGateBlockers: {
        invalid_lottery_target: '活动 URL 不可执行',
        lottery_action_plan_required: '缺少动作计划',
        lottery_rule_review_required: '活动规则待确认',
        lottery_required_actions_missing: '未识别参与动作',
        no_calibrated_ready_account: '无校准账号',
        real_adapter_not_enabled: '适配器未启用',
        global_real_run_disabled: '总开关关闭',
        recent_complete_probe_required: '缺近期完整探针',
        recent_shadow_run_required: '缺近期 Shadow',
        recent_account_risk_event: '账号近期有风险',
      },
      strategyReasons: {
        active_run_in_progress: '已有运行中任务',
        no_safe_account: '无安全账号',
        circuit_breaker_open: '熔断器开启',
        dry_validation_needed: '需要 dry-run 验证',
        shadow_validation_needed: '需要 shadow-run 验证',
        real_gate_ready: '真实执行门禁已满足',
        adapter_not_ready: '适配器未就绪',
        probe_not_ready: '探针未就绪',
        real_run_disabled: 'real-run 关闭',
        real_gate_not_ready: '真实执行门禁未满足',
        recent_platform_risk: '近期平台风险',
        recent_failures: '近期失败',
        high_value: '高价值目标',
        platform_knowledge_used: '已使用平台经验',
        low_knowledge_confidence: '经验置信度偏低',
        historical_win_rate_used: '已使用历史中奖率',
        account_reputation_used: '已使用账号信誉',
        account_reputation_low: '账号信誉偏低',
      },
    },
    strategy: {
      eyebrow: '决策运行时',
      title: '策略决策台',
      subtitle: '按优先级分层展示策略队列；每条建议可展开评分构成。仅展示建议，真实执行仍走人工确认门禁。',
      totalTargets: '候选目标',
      actNow: '立即处理',
      strong: '强候选',
      holding: '暂缓',
      rank: '排名',
      target: '目标',
      score: '策略分',
      expectedValue: '期望值',
      mode: '建议模式',
      reasons: '原因',
      action: '操作',
      explain: '解释',
      emptyTier: '该层暂无目标',
      explainTitle: '决策解释',
      explaining: '正在生成解释…',
      modeDecision: '模式决策',
      scoreBreakdown: '评分构成',
      modeMultiplier: '模式系数',
      total: '总分',
      winProbability: '中奖概率估计',
      baseline: '基线概率',
      observedRate: '观测中奖率',
      confidenceWeight: '置信权重',
      blended: '融合概率',
      trustScore: '信任分',
      accountTrust: '账号信任',
      confidenceBonus: '置信加成',
      riskPenalty: '风险扣分',
      trustTotal: '信任分',
      knowledgeConfidence: '经验置信度',
      safetyNote: '策略层只建议执行模式与排序，不会自动越过 real-run 门禁；真实执行需管理员确认。',
      tier: { S: '立即处理（S）', A: '强候选（A）', B: '低优先 / 待验证（B）', hold: '暂缓 / 阻塞' },
      components: {
        base_value: '基础价值',
        validation_bonus: '验证加成',
        knowledge_bonus: '经验加成',
        account_bonus: '账号加成',
        expected_value_bonus: '期望值加成',
        probability_bonus: '概率加成',
        risk_penalty: '风险扣分',
      },
      knowledgeParts: {
        lottery_sample: '活动样本',
        result_labels: '结果标签',
        task_runs: '任务执行',
        shadow_success: 'Shadow 成功',
        real_success: 'Real 成功',
      },
      units: { targets: '目标', tierS: 'S 层', tierA: 'A 层', hold: '暂缓' },
    },
    knowledge: {
      eyebrow: '经验运行时',
      title: '经验知识库',
      subtitle: '数据成熟度、平台与账号画像、学习缺口清单。数据来自最近 30 天事件、目标、执行与风险记录。',
      maturity: '数据成熟度',
      events: '事件量',
      resultLabels: '结果标签',
      shadowSuccess: 'Shadow 成功',
      platformProfiles: '平台画像',
      accountProfiles: '账号画像',
      learningGaps: '学习缺口',
      platform: '平台',
      confidence: '置信度',
      lotteries: '活动数',
      winRate: '中奖率',
      runs: '执行数',
      successRate: '成功率',
      shadowReal: 'Shadow / Real',
      risk: '风险',
      account: '账号',
      reputation: '信誉',
      noData: '暂无平台数据',
      noAccounts: '暂无账号画像',
      noGaps: '暂无学习缺口',
      levels: { learning_ready: '可学习', usable: '可用', warming: '预热中', cold_start: '冷启动' },
      units: { events: '事件', labels: '标签', runs: '次' },
    },
    risk: {
      eyebrow: '安全',
      title: '风险事件',
      proxyPool: '代理池',
      activeExits: '可用出口',
      coolingExits: '冷却出口',
      assigned: '已分配',
      proxyExits: '代理出口',
      proxyUrl: '代理 URL',
      type: '类型',
      provider: '服务商',
      region: '地区',
      addProxy: '添加代理',
      proxy: '代理',
      status: '状态',
      health: '健康度',
      cooldown: '冷却',
      account: '账号',
      action: '操作',
      unassigned: '未分配',
      cool30m: '冷却 30 分钟',
      active: '启用',
      dead: '失效',
      noProxies: '暂无代理出口',
      time: '时间',
      detail: '详情',
      noEvents: '暂无风险事件',
      added: '代理已添加',
      cooled: '代理 P{id} 已进入冷却',
      statusSet: '代理 P{id} 已标记为 {status}',
      check: '检测',
      lastCheck: '最后检测',
      checkOk: '代理 P{id} 检测通过，延迟 {latency}ms',
      checkFailed: '代理 P{id} 检测失败：{error}',
      units: {
        exits: '出口',
        usable: '可用',
        cooldown: '冷却',
        accounts: '账号',
      },
    },
    tasks: {
      eyebrow: '实时流',
      title: '实时任务事件',
      connected: '已连接',
      connecting: '连接中',
      disconnected: '已断开',
      waiting: '等待事件',
      streamReady: '实时事件流已连接',
      streamDisconnected: '实时事件流已断开，浏览器将自动重试',
      badPayload: '收到无法解析的实时事件',
      task: '任务',
      account: '账号',
      phase: '阶段',
    },
    events: {
      eyebrow: '运行时记忆',
      title: '事件时间线',
      filters: '筛选',
      latest: '最新事件',
      aggregate: '聚合',
      eventType: '事件类型',
      correlation: '关联 ID',
      actor: '操作者',
      service: '服务',
      payload: '载荷',
      time: '时间',
      allAggregates: '全部聚合',
      clearFilters: '清空筛选',
      loading: '加载中',
      noEvents: '暂无事件',
      aggregates: {
        account: '账号',
        lottery: '抽奖',
        task: '任务',
        risk: '风险',
        browser: '浏览器',
        worker: 'Worker',
        notification_channel: '通知通道',
        notification_log: '通知日志',
        platform: '平台',
        source: '发现源',
        lottery_import: '目标导入',
        system: '系统',
      },
    },
    deploy: {
      eyebrow: '运维',
      title: '运维与通知',
      runtime: '运行时',
      currentVersion: '当前版本',
      globalBreaker: '全局熔断器',
      workerReload: '重载 Worker',
      reloadArmed: '确认发送重载信号',
      runtimeRollback: '运行态紧急回滚',
      rollbackHint: '关闭 real-run，打开全局熔断器，撤销排队中的真实任务，并通知 Worker 重新加载。',
      rollbackReason: '回滚原因',
      rollbackArmed: '确认执行运行态回滚',
      applyRollback: '执行回滚',
      rollbackDone: '运行态回滚已执行，已撤销 {count} 个排队 real-run。',
      uploadPackage: '上传更新包',
      hmacSignature: 'HMAC 签名',
      notificationTest: '通知测试',
      channel: '通道',
      testTitle: '标题',
      content: '内容',
      sendTest: '发送测试',
      missingSelected: '当前通道缺少密钥。请在下方补齐配置后再发送测试。',
      notificationHealth: '通知健康',
      configured: '已配置',
      missingSecrets: '缺少密钥',
      last: '上次',
      sent: '已发送',
      failed: '失败',
      noLogs: '无日志',
      healthy: '健康',
      needsCheck: '需检查',
      notSet: '未设置',
      configuredChannels: '已配置通知通道：{count}。账号风险、登录校准、任务结果和手动测试共用该分发路径。',
      lastDispatchSkip: '上次跳过分发：{title}',
      notificationGuide: '通知配置说明',
      missing: '缺失',
      testEndpoint: '测试接口：{endpoint}。API 不会回显密钥。',
      envBundle: '通知 .env 配置包',
      productionReady: '至少一个通知通道已可用，可承接生产告警。',
      productionMissing: '尚未配置可用通知通道，生产告警会被记录但不会外发。',
      missingRequired: '缺失变量',
      minimumEnv: '最小可用配置',
      fullEnv: '全部通道配置',
      none: '无',
      saveSecret: '保存密钥',
      clearSecret: '清空密钥',
      secretSaved: '{channel} 密钥已保存',
      secretCleared: '{channel} 密钥已清空',
      secretRequired: '请至少填写一个密钥字段',
      secretConfigured: '已配置，输入新值可覆盖',
      secretPlaceholder: '粘贴密钥或 Webhook URL',
      secretBundle: '批量粘贴通知 .env',
      secretBundlePlaceholder: '支持粘贴多行，例如：\nSERVERCHAN_KEY=...\nFEISHU_WEBHOOK=https://...\nGENERIC_WEBHOOK_URL=https://...\nTELEGRAM_BOT_TOKEN=...\nTELEGRAM_CHAT_ID=...',
      saveSecretBundle: '批量保存密钥',
      useMinimumEnv: '使用最小模板',
      secretBundleRequired: '请粘贴至少一个通知密钥',
      secretBundleSaved: '通知密钥已保存：{keys}',
      adapterBuilder: '适配器配置构建器',
      selectorJson: '选择器 JSON',
      generateBase64: '生成 Base64',
      saveRuntimeSelectors: '保存到运行时',
      clearRuntimeSelectors: '清空运行时',
      resetSample: '重置示例',
      envOutput: '.env 输出',
      envPlaceholder: '确认探针证据中的选择器后生成 Base64。',
      preferredKey: '推荐键：{key}。真实动作启用前必须覆盖全部四个阶段。',
      probeCandidates: '探针选择器候选',
      probe: '探针',
      platform: '平台',
      activity: '活动',
      visiblePhases: '可见阶段',
      action: '操作',
      useDraft: '使用草稿',
      noProbeCandidates: '暂无可用探针选择器结果。请先使用低风险账号登录并运行探针。',
      notificationLogs: '通知日志',
      result: '结果',
      created: '创建时间',
      noNotificationLogs: '暂无通知日志',
      reloadSent: 'Worker 重载信号已发送',
      operationFailed: '操作失败',
      uploadReady: '填写 HMAC 签名后选择更新包上传。',
      uploadDone: '更新包已上传',
      uploadFailed: '上传失败',
      notificationQueued: '通知已排队：N{logId}',
      selectorEncoded: '适配器选择器配置已编码。请将生成的配置行写入 .env 后重建服务。',
      selectorSaved: '已保存 {count} 个平台的运行时选择器配置',
      selectorCleared: '{platform} 运行时选择器已清空',
      invalidSelector: '选择器 JSON 无效：{message}',
      draftLoaded: '已从探针 {probe} 载入选择器草稿。生成 Base64 前请复核。',
      loadFailed: '运维数据加载失败：{message}',
      planned: '计划中',
      realRunReadiness: '{platform} 真实执行准备度',
      realRunReadinessHint: '按账号、探针、选择器、Shadow 和总开关检查真实执行前置条件。',
      readyForReal: '可真实执行',
      needsAction: '需处理',
      ready: '就绪',
      loadProbeDraft: '载入探针草稿',
      workflowTarget: '当前活动',
      currentSafeAction: '当前安全步骤',
      workflowState: '执行状态',
      workflowIdle: '等待操作',
      noTargetForPlatform: '暂无 {platform} 活动',
      invalidTargetsIgnored: '已忽略首页或测试 URL，请到任务编排添加可执行的活动链接。',
      noProbeDraft: '没有可用的完整探针草稿',
      probeInProgress: '探针 {id} 执行中',
      shadowInProgress: 'Shadow {id} 执行中',
      probeRunning: '探针执行中',
      shadowRunning: 'Shadow 执行中',
      workflowSubmitting: '正在提交',
      runSafeNextStep: '执行：{action}',
      reviewRealRunTask: '复核真实执行',
      reviewRealRunSwitchButton: '复核 Real-run 开关',
      workflowQueued: '{action} 已排队，任务 {id}',
      reviewRealRunSwitch: '安全证据已齐备。请复核顶部 Real-run 开关并手动确认。',
      realRunReadyNotice: '真实执行门禁已就绪，请前往抽奖任务页选择活动和账号后确认执行。',
      workflowManualReview: '当前步骤需要人工复核，请按门禁提示处理。',
      readinessSteps: {
        targetTitle: '有效活动',
        targetDetail: '必须是平台校验通过的可执行抽奖链接（如视频、动态、微博或笔记），首页/个人主页不能作为执行目标。',
        accountTitle: '安全账号',
        accountDetail: '至少需要一个已校准且有有效凭据的 {platform} 账号。',
        probeTitle: '完整探针',
        probeDetail: '24 小时内需要完成关注、点赞、评论、转发四阶段探针。',
        selectorTitle: '运行时选择器',
        selectorDetail: '根据探针证据保存该平台的适配器选择器。',
        shadowTitle: 'Shadow-run 证据',
        shadowDetail: '真实执行前先在无副作用模式下验证页面和登录态。',
        globalTitle: '全局开关',
        globalDetail: 'real-run 总开关默认关闭，只应在证据齐全后由管理员确认开启。',
      },
    },
    experiments: {
      eyebrow: '决策运行时',
      title: '实验运行时',
      subtitle: '对比 dry-run / shadow-run 策略分支，结果仅供参考；风险信号会自动停止相关分支，真实执行仍受 real-run 门禁约束。',
      totalExperiments: '实验总数',
      running: '运行中',
      stopped: '已停止',
      experimentList: '实验列表',
      id: '实验 ID',
      name: '名称',
      platform: '平台',
      mode: '模式',
      status: '状态',
      branches: '分支',
      action: '操作',
      details: '详情',
      noExperiments: '暂无实验',
      detailTitle: '实验详情',
      loadingDetail: '正在加载详情…',
      overview: '概览',
      hypothesis: '假设',
      stoppedReason: '停止原因',
      stopExperiment: '停止实验',
      guardrailsTitle: '安全护栏',
      noGuardrails: '暂无安全护栏说明',
      comparison: '分支对比',
      comparisonStatus: '对比状态',
      comparisonStatuses: {
        insufficient_data: '样本不足',
        leader_found: '已发现领先分支',
      },
      leader: '领先分支',
      minSamples: '最小样本数',
      branchStats: '分支统计',
      branchKey: '分支',
      runs: '执行数',
      winRate: '中奖率',
      participationRate: '参与率',
      failureRate: '失败率',
      riskRate: '风险率',
      stopSignal: '停止信号',
      ok: '正常',
      stopBranch: '停止分支',
      noBranches: '暂无分支数据',
      safetyNote: '实验层仅提供对比建议，不会自动派发或越过 real-run 门禁；停止操作需要管理员/操作员确认。',
      stopReasonPrompt: '请输入停止原因',
      branchStopped: '分支 {branch} 已停止',
      experimentStopped: '实验已停止',
      units: { experiments: '个' },
      guardrails: {
        captcha_or_ratelimit_stops_branch: '验证码或限流信号将自动停止对应分支',
        results_are_advisory_only: '结果仅供参考，不会自动执行',
        runs_in_dry_or_shadow_only: '仅在 dry-run / shadow-run 模式下运行',
        real_run_requires_admin_and_evidence_gate: 'real-run 实验仍需管理员确认与证据门禁',
        comment_content_from_controlled_template_pool: '评论内容取自受控模板池',
      },
      stopReasons: {
        hard_risk_signal: '触发硬风险信号（验证码/封禁）',
        risk_rate_exceeded: '风险率超过阈值',
      },
    },
    riskIntel: {
      eyebrow: '风险情报',
      title: '风险情报预测',
      subtitle: '账号 24 小时风险预测仅供参考，只会让派发更保守，绝不会放宽 real-run 门禁。',
      forecastTable: '账号风险预测',
      account: '账号',
      platform: '平台',
      status: '状态',
      reputation: '信誉',
      riskScore: '风险分',
      forecast24h: '24 小时预测',
      forecastBand: '预测等级',
      recommendedAction: '建议动作',
      reasons: '原因',
      noData: '暂无风险情报数据',
      units: { accounts: '账号' },
      bands: {
        high: '高风险',
        elevated: '中高风险',
        moderate: '中等风险',
        low: '低风险',
      },
      actions: {
        allow: '正常放行',
        dry_run_only: '仅 dry-run',
        cooldown: '冷却',
        relogin: '需重新登录',
        manual_review: '人工复核',
        block: '阻断',
      },
      reasonCodes: {
        hard_risk_signal_24h: '24 小时内出现硬风险信号',
        account_locked_state: '账号处于冻结/封禁状态',
        login_required_state: '账号需重新登录',
        cooling_state: '账号处于冷却状态',
        calibration_not_succeeded: '最近一次校准未成功',
        daily_volume_high: '当日任务量偏高',
        recent_risk_events: '近期存在风险事件',
        consecutive_failures: '连续失败次数偏高',
        low_reputation: '账号信誉偏低',
      },
    },
    learning: {
      eyebrow: '学习运行时',
      title: '学习与预测',
      subtitle: '基于透明的线性模型给出建议性成功概率，仅供参考，不会放宽 real-run 门禁。',
      modelCard: '模型卡片',
      modelVersion: '模型版本',
      featureSetVersion: '特征集版本',
      modelType: '模型类型',
      bias: '偏置',
      feature: '特征',
      weight: '权重',
      description: '说明',
      noModel: '暂无模型数据',
      loadingModel: '正在加载模型…',
      predictions: '目标预测',
      lottery: '活动',
      platform: '平台',
      valueScore: '价值评分',
      probability: '成功概率',
      confidenceBand: '置信等级',
      topDrivers: '主要驱动因子',
      noPredictions: '暂无预测数据',
      safetyNote: '预测结果为建议性概率，不构成执行依据；真实执行仍需通过 real-run 门禁与人工确认。',
      bands: {
        high: '高',
        moderate: '中',
        low: '低',
        very_low: '极低',
      },
      features: {
        value: '目标价值',
        win_rate: '历史中奖率',
        knowledge_confidence: '经验置信度',
        account_reputation: '账号信誉',
        validation_depth: '验证深度',
        recent_risk: '近期风险',
      },
    },
    governance: {
      eyebrow: '治理运行时',
      title: '治理与门禁策略',
      subtitle: 'real-run 门禁以可版本化、可重放的策略呈现：评估是只读操作，永不派发任务或放宽门禁，且默认失败关闭。',
      activePolicy: '当前策略',
      policyKey: '策略键',
      policyVersion: '版本',
      required: '是否必需',
      remediation: '处理建议',
      yes: '是',
      no: '否',
      noGates: '暂无门禁项',
      loadingPolicy: '正在加载策略…',
      policyVersions: '策略版本历史',
      note: '备注',
      active: '生效',
      createdAt: '创建时间',
      noVersions: '暂无策略版本',
      evaluateGate: '评估 Real-run 门禁',
      evaluateHint: '输入活动 ID 评估其 real-run 门禁状态；评估会记录一条可重放的决策。',
      lotteryIdPlaceholder: '活动 ID',
      evaluate: '评估',
      evaluating: '评估中…',
      invalidLotteryId: '请输入有效的活动 ID',
      outcome: '结果',
      decisionId: '决策 ID',
      gateChecklist: '门禁检查项',
      failedReasons: '未通过原因',
      nextAction: '下一步建议',
      recentDecisions: '最近决策记录',
      subject: '对象',
      action: '操作',
      replay: '重放',
      noDecisions: '暂无决策记录',
      replayMatch: '重放结果一致',
      replayMismatch: '重放结果不一致',
      versionMatch: '策略版本一致',
      versionMismatch: '策略版本不一致',
      gateCode: '门禁项',
      outcomes: {
        allow: '允许',
        block: '阻断',
      },
      gates: {
        global_real_run_enabled: { label: '全局 real-run 已开启', remediation: '需开启全局开关' },
        circuit_breaker_closed: { label: '熔断器未触发', remediation: '需复查熔断器' },
        valid_lottery_target: { label: '活动目标有效', remediation: '需添加有效目标' },
        action_plan_reviewed: { label: '动作计划已确认', remediation: '需确认活动规则' },
        calibrated_account_available: { label: '存在已校准可用账号', remediation: '需添加账号' },
        real_adapter_enabled: { label: '真实动作适配器已启用', remediation: '需配置适配器' },
        recent_complete_probe: { label: '近期存在完整探针', remediation: '需运行探针' },
        recent_shadow_run: { label: '近期存在 Shadow 执行', remediation: '需运行 Shadow' },
        no_recent_account_risk: { label: '账号近期无风险事件', remediation: '需复查风险' },
      },
      remediations: {
        enable_real_run: '开启全局 real-run 开关',
        review_breaker: '复查熔断器状态',
        add_target: '添加有效活动目标',
        review_rule: '确认活动规则与动作计划',
        add_account: '添加并校准账号',
        configure_adapter: '配置真实动作适配器',
        probe: '运行适配器探针',
        shadow_run: '运行 Shadow 执行',
        review_risk: '复查账号风险',
        real_run: '可派发真实任务',
      },
    },
    transitions: {
      eyebrow: '迁移运行时',
      title: '策略迁移图谱',
      subtitle: '每一次策略版本变更都会留下一条不可篡改的迁移记录:为什么改、改了什么、如何回退、是收紧还是放宽。发布新版本永不改变线上行为,只有"激活"才会。',
      safetyBanner: '发布不等于生效:只有点击"激活"才会改变 real-run 门禁的实际评估版本。任何放宽门禁的变更都必须填写书面理由,并会被标记为需要额外复核。',
      activeVersion: '当前生效版本',
      chainTitle: '版本迁移链',
      noChain: '尚无迁移记录,当前版本为内置默认策略。',
      active: '当前生效',
      activated: '已激活',
      pendingActivation: '已发布,待激活',
      activate: '激活',
      activating: '激活中…',
      classification: '分类',
      classifications: {
        tightening: '收紧',
        loosening: '宽松化',
        neutral: '中性',
      },
      extraReview: '需额外复核',
      viewDiff: '查看差异',
      hideDiff: '收起差异',
      addedGates: '新增门禁',
      removedGates: '移除门禁',
      changedGates: '必需性变化',
      noGateChanges: '无相关变化',
      required: '必需',
      optional: '可选',
      impactScope: '影响面',
      rollbackCondition: '回退条件',
      loosJustification: '宽松化理由',
      publishTitle: '提案新策略版本',
      publishHint: '编辑下方 JSON 形成新版本草案,填写变更原因与回退条件;提交后该版本仅被记录与发布,不会自动生效。',
      definitionLabel: '策略定义(JSON)',
      seedFromActive: '基于当前生效策略生成',
      reasonCodeLabel: '变更原因',
      rollbackLabel: '回退条件',
      rollbackPlaceholder: '例如:若误报率超过 5% 则回退到上一版本',
      loosJustificationLabel: '宽松化理由(若此变更放宽任何门禁则必填)',
      noteLabel: '备注',
      publish: '发布版本',
      publishing: '发布中…',
      publishResult: '发布结果',
      invalidJson: '策略定义必须是合法 JSON',
      rollbackRequired: '必须填写回退条件',
      publishSuccess: '策略版本已发布(尚未生效)',
      activateSuccess: '策略版本已激活',
      reasons: {
        experiment_result: '实验结果',
        risk_tightening: '风险收紧',
        manual_review: '人工复核',
        incident_response: '事件响应',
        scheduled_review: '定期复核',
      },
    },
    status: {
      ready: '可用',
      gray: '灰度',
      login_required: '需登录',
      warming: '校验中',
      cooling: '冷却中',
      frozen: '冻结',
      executing: '执行中',
      pending: '待处理',
      claimed: '已领取',
      running: '运行中',
      participated: '已参与',
      won: '中奖',
      lost: '未中',
      succeeded: '成功',
      failed: '失败',
      queued: '排队中',
      opening: '打开中',
      waiting_scan: '等待扫码',
      scanned: '已扫码，等待确认',
      confirmed: '已确认',
      expired: '已过期',
      banned: '封禁',
      unknown: '未知',
      draft: '草稿',
      stopped: '已停止',
      completed: '已完成',
    },
  },
  en: {
    nav: {
      dashboard: 'Overview',
      accounts: 'Accounts',
      lotteries: 'Tasks',
      strategy: 'Strategy',
      knowledge: 'Knowledge',
      experiments: 'Experiments',
      riskIntel: 'Risk Intelligence',
      learning: 'Learning',
      governance: 'Governance',
      transitions: 'Transition Graph',
      tasks: 'Live stream',
      events: 'Event timeline',
      risk: 'Safety',
      deploy: 'Operations',
    },
    common: {
      local: 'Local runtime',
      language: 'Language',
      theme: 'Theme',
      light: 'Light',
      dark: 'Dark',
      system: 'System',
      refresh: 'Refresh',
      delete: 'Delete',
      cancel: 'Cancel',
    },
    accounts: {
      eyebrow: 'Account access',
      title: 'Login control center',
      healthRecheck: 'Health recheck',
      qrLogin: 'QR login',
      qrBroker: 'Scan-to-login broker',
      platform: 'Platform',
      generateQr: 'Generate QR',
      qrOpening: 'Opening the platform login page and capturing the QR screen...',
      qrEmpty: 'Choose a platform, generate a QR login session, then scan it with the official app.',
      qrOfficialAlt: 'Official Bilibili login QR code',
      qrOfficialHint: 'Scan with the official Bilibili app and confirm on your phone.',
      cookieLogin: 'Cookie login',
      cookieImport: 'Import raw Cookie or JSON Cookie',
      cookie: 'Cookie',
      cookiePlaceholder: 'Paste a Cookie header directly, for example: SESSDATA=...; bili_jct=...; DedeUserID=...',
      importCreate: 'Import and create',
      accountPool: 'Account pool',
      refreshCredentials: 'Refresh existing credentials',
      noAccounts: 'No accounts yet',
      noRefresh: 'Create an account before refreshing credentials.',
      imported: 'Imported',
      missing: 'Missing',
      notChecked: 'Not checked',
      evidence: 'Evidence',
      noRisk: 'No recent risk',
      accountCreated: 'Account created',
      importQueued: 'Account created and queued for calibration',
      credentialSaved: 'Cookie saved and queued for calibration',
      statusUpdated: 'Account status updated',
      calibrationQueued: 'Account calibration queued',
      healthDone: 'Account health recheck completed',
      deleteConfirm: 'Delete this account and its related records? This cannot be undone.',
      deleted: 'Account deleted',
      rawCookieHint: 'Raw browser Cookie headers, multiline Cookie text, and JSON Cookie exports are supported.',
      runtime: 'Runtime',
    },
    dashboard: {
      eyebrow: 'Runtime',
      title: 'Operations overview',
      workersOnline: 'Workers online',
      pendingTasks: 'Pending tasks',
      readyAccounts: 'Ready accounts',
      coolingAccounts: 'Cooling accounts',
      todayExecutions: 'Today executions',
      memory: 'Memory',
      dryRunPlatforms: 'Dry-run platforms',
      realRunPlatforms: 'Real-run platforms',
      safeAccounts: 'Safe accounts',
      notifyChannels: 'Notify channels',
      proxyExits: 'Proxy exits',
      risk24h: 'Risk 24h',
      nextActions: 'Next actions',
      noActions: 'No remediation actions are currently required',
      strategyAdvice: 'Review & strategy advice',
      strategyWindow: 'Generated from executions, risk, target pool, and notification state over the last {days} days.',
      noStrategyAdvice: 'No strategy advice right now',
      productionReady: 'Production ready',
      productionGate: 'Production gate',
      blocked: 'Blocked',
      platformReadiness: 'Platform readiness',
      platform: 'Platform',
      dryRun: 'Dry run',
      realRun: 'Real run',
      probe: 'Probe',
      blockers: 'Blockers',
      noProbe: 'No probe',
      clear: 'Clear',
      loading: 'Readiness data is loading',
      kickerLogin: 'Login',
      kickerSafety: 'Safety',
      kickerNotify: 'Notify',
      loginTitle: 'QR + Cookie session',
      loginText: 'Accounts enter the pool only after a valid encrypted credential is available.',
      safetyTitle: 'Rate window + daily cap',
      safetyText: 'Worker blocks unsafe runs and moves risky accounts to cooling or login-required states.',
      notifyTitle: 'ServerChan / Feishu / Webhook / Telegram',
      notifyText: 'Each delivery is logged so silent notification failure does not hide task results.',
      blockersMap: {
        'adapter probe is incomplete': 'adapter probe is incomplete',
        'no calibrated ready account': 'no calibrated ready account',
        'real adapter not enabled': 'real adapter not enabled',
        'global real-run switch is disabled': 'global real-run switch is disabled',
        adapter_probe_incomplete: 'adapter probe is incomplete',
        no_calibrated_ready_account: 'no calibrated ready account',
        real_adapter_not_enabled: 'real adapter not enabled',
        global_real_run_disabled: 'global real-run switch is disabled',
      },
      actionsMap: {
        configureNotificationTitle: 'Configure at least one notification channel',
        configureNotificationDetail: 'Set SERVERCHAN_KEY, FEISHU_WEBHOOK, GENERIC_WEBHOOK_URL, or TELEGRAM_BOT_TOKEN plus TELEGRAM_CHAT_ID, then send a notification test.',
        reviewRiskTitle: 'Review recent account risk signals',
        reviewRiskDetail: 'Open Safety, inspect the latest risk events, and recalibrate any affected account before returning it to the ready pool.',
        addProxyTitle: 'Add isolated proxy exits for production accounts',
        addProxyDetail: 'Open Safety, add one proxy exit per account, and keep risky exits in cooldown before enabling higher-volume multi-platform automation.',
        addAccountTitle: 'Add a calibrated safe account for {platform}',
        addAccountDetail: 'Use QR login or cookie import, then run account calibration so dry-run dispatch can safely auto-pick the account.',
        completeProbeTitle: 'Complete adapter probe for {platform}',
        completeProbeDetail: 'Probe a low-risk real lottery page until follow, like, comment, and repost phases are visible; then review the recommended selector config.',
        enableAdapterTitle: 'Enable real action adapter for {platform}',
        enableAdapterDetail: 'After a safe account is calibrated, configure selectors verified by adapter probe evidence.',
        dryRunOnlyTitle: 'Keep production dispatch in dry-run mode',
        dryRunOnlyDetail: 'Dry-run validation can continue, but real execution should remain gated until accounts, probe evidence, adapters, and safety checks pass.',
      },
      checksMap: {
        worker_onlineTitle: 'At least one worker is online',
        worker_onlineDetail: 'A visible worker consumer or DB heartbeat is required before tasks can execute.',
        real_run_global_switchTitle: 'Global real-run switch is controlled',
        real_run_global_switchDetail: 'Real execution is disabled by default and should be enabled only after production approval.',
        notification_readyTitle: 'At least one notification channel is available',
        notification_readyDetail: 'Production alerts need ServerChan, Feishu, Webhook, or Telegram delivery.',
        target_pool_readyTitle: 'Dispatchable lottery targets exist',
        target_pool_readyDetail: 'The target pool needs at least one pending or claimed target.',
        all_platforms_dry_readyTitle: 'All platforms have dry-run accounts',
        all_platforms_dry_readyDetail: 'Multi-platform dry-run requires at least one calibrated ready account per platform.',
        real_run_availableTitle: 'At least one platform can run real actions',
        real_run_availableDetail: 'Real execution requires accounts, probe evidence, adapters, and the global gate together.',
        active_proxy_exitTitle: 'An active proxy exit is available',
        active_proxy_exitDetail: 'Account isolation needs at least one active proxy exit outside cooldown.',
        safe_accounts_proxiedTitle: 'Ready accounts have proxy exits',
        safe_accounts_proxiedDetail: 'Production accounts should bind usable proxy exits to reduce account linkage risk.',
        recent_risk_clearTitle: 'No account risk in the last 24 hours',
        recent_risk_clearDetail: 'Recent risk events need review and possibly account recalibration.',
      },
      strategyMap: {
        configure_notificationsTitle: 'Configure notification before autonomous runs',
        configure_notificationsDetail: 'No external notification channel is configured, so wins, failures, captcha, or bans may only be visible in logs.',
        run_shadow_before_realTitle: 'Run shadow-run before real-run',
        run_shadow_before_realDetail: 'Pending targets exist, but no successful shadow-run was recorded in the last 7 days.',
        promote_dry_to_shadowTitle: 'Promote dry-run validation into shadow-run',
        promote_dry_to_shadowDetail: 'Dry-run is succeeding, so the next safe step is opening real pages with no side effects to validate login state and risk signals.',
        complete_real_gateTitle: 'Complete the real-run gate after shadow evidence',
        complete_real_gateDetail: 'Shadow-run evidence exists, but no platform currently satisfies real-run readiness.',
        review_failed_runsTitle: 'Review failed runs before increasing volume',
        review_failed_runsDetail: 'Recent task failures should be inspected through evidence screenshots and event timeline before scaling the scheduler.',
        cooldown_risky_accountsTitle: 'Cooldown and recalibrate risky accounts',
        cooldown_risky_accountsDetail: 'Risk events were recorded recently; affected accounts should be cooled, recalibrated, or assigned safer proxy exits.',
        prioritize_high_value_targetsTitle: 'Prioritize high-value pending targets',
        prioritize_high_value_targetsDetail: 'High-score pending targets exist and safe accounts are available; dispatch order should favor expected value after shadow-run clears.',
        recover_stale_tasksTitle: 'Recover stale active tasks',
        recover_stale_tasksDetail: 'Queued or running tasks older than 30 minutes were found; inspect Worker health and recovery daemon behavior.',
        continue_controlled_real_runTitle: 'Continue controlled real-run cadence',
        continue_controlled_real_runDetail: 'Recent real-run tasks succeeded and no urgent blocker was detected by the strategy review.',
      },
      units: {
        nodes: 'nodes',
        items: 'items',
        accounts: 'accounts',
        runs: 'runs',
        configured: 'configured',
        calibrated: 'calibrated',
        events: 'events',
        of: 'of',
      },
    },
    lotteries: {
      eyebrow: 'Workflow',
      title: 'Task orchestration',
      autoPick: 'Auto-pick calibrated account',
      calibrated: 'calibrated',
      strategyQueue: 'Strategy queue',
      strategyQueueHint: 'Ranked by target value, account readiness, dry/shadow evidence, risk, and failed runs.',
      rank: 'Rank',
      priorityScore: 'Strategy score',
      expectedValue: 'Expected value',
      recommendedMode: 'Recommended mode',
      recommendedAccount: 'Recommended account',
      knowledge: 'Knowledge',
      reasons: 'Reasons',
      dispatchRecommended: 'Dispatch suggested',
      noStrategyTargets: 'No schedulable targets',
      dryRun: 'Dry run',
      shadowRun: 'Shadow run',
      real: 'Real',
      dry_run: 'Dry run',
      shadow_run: 'Shadow run',
      real_run: 'Real',
      blocked: 'Blocked',
      qrLogin: 'QR login',
      cookieLogin: 'Cookie login',
      realActions: 'Real actions',
      adapter: 'Adapter',
      safeAccounts: 'Safe accounts',
      phases: 'Phases',
      adapterLoading: 'Adapter diagnostics loading',
      cookieDomain: 'Cookie domain',
      manualIntake: 'Manual activity intake',
      platform: 'Platform',
      activityUrl: 'Activity URL',
      score: 'Score',
      create: 'Create',
      discoverySources: 'Discovery sources',
      type: 'Type',
      interval: 'Interval',
      sourceValue: 'Source value',
      sourceValuePlaceholder: 'URL list or discovery condition',
      upUidPlaceholder: 'Enter the numeric Bilibili creator UID',
      saveSource: 'Save source',
      scanNow: 'Scan now',
      sourceSaved: 'Discovery source saved',
      scanComplete: 'Scan complete: {inserted} inserted, {found} found, {failed} failed',
      activityCreated: 'Activity created',
      defaultPlatform: 'Default platform',
      defaultScore: 'Default score',
      uploadTargets: 'Upload targets',
      targetList: 'Target list',
      targetPlaceholder: 'One URL per line, or platform,url,score,expires_at\nhttps://www.bilibili.com/video/BV...\nbilibili,https://t.bilibili.com/123456789,80,2026-06-30 23:59:59',
      importTargets: 'Import targets',
      targetsImported: 'Targets imported: {created_count} created, {duplicate_count} duplicates, {invalid_count} invalid',
      targetFileLoaded: 'Target file loaded: {name}',
      importSummary: 'Processed {received} lines, {created_count} created, {duplicate_count} duplicates, {invalid_count} invalid',
      dispatchQueued: 'Task dispatched',
      probeQueued: 'Adapter probe queued',
      resultUpdated: 'Result updated',
      activityPool: 'Activity pool',
      url: 'URL',
      rulePlan: 'Rule plan',
      ruleReady: 'Rule confirmed',
      ruleNeedsReview: 'Review required',
      ruleTextPlaceholder: 'Original activity rules',
      confirmRule: 'Confirm action plan',
      ruleSaved: 'Activity action plan saved',
      suggestRule: 'Suggest action plan',
      suggesting: 'Suggesting…',
      suggestionConfidence: 'Suggestion confidence: {value}%',
      suggestionAmbiguous: 'Ambiguous wording detected — please review manually',
      suggestionUnsupportedPrefix: 'Needs manual handling: ',
      actions: {
        followed: 'Follow',
        liked: 'Like',
        commented: 'Comment',
        reposted: 'Repost',
      },
      unsupportedActions: {
        mention_friends: 'Mention friends (manual @ required)',
        favorited: 'Favorite/collect (manual action required)',
      },
      status: 'Status',
      expires: 'Expires',
      action: 'Action',
      noSafeAccount: 'No safe account',
      adapterPending: 'Adapter pending',
      dispatchReal: 'Dispatch real',
      dispatchDry: 'Dispatch dry',
      dispatch_dry_run: 'Dispatch dry',
      dispatch_shadow_run: 'Dispatch shadow',
      dispatch_real_run: 'Dispatch real',
      won: 'Won',
      lost: 'Lost',
      probe: 'Probe',
      noActivities: 'No activities',
      noSources: 'No discovery sources',
      adapterProbes: 'Adapter probes',
      account: 'Account',
      activity: 'Activity',
      visiblePhases: 'Visible phases',
      quality: 'Quality',
      evidence: 'Evidence',
      raw: 'Raw',
      openProbe: 'Open probe',
      noAdapterProbes: 'No adapter probes',
      executionRuns: 'Execution runs',
      task: 'Task',
      mode: 'Mode',
      openEvidence: 'Open evidence',
      noRuns: 'No runs',
      lastScan: 'Last scan',
      active: 'Active',
      realAdapterMissing: 'Real adapter is not available for this platform yet.',
      realGate: 'Real gate',
      gateReady: 'Ready',
      gateBlocked: 'Evidence missing',
      gateUnknown: 'Unknown',
      nextActions: {
        add_target: 'Add a real target',
        review_rule: 'Review activity rule',
        add_account: 'Add account first',
        configure_adapter: 'Configure adapter',
        probe: 'Run probe first',
        shadow_run: 'Run shadow first',
        review_risk: 'Review risk first',
        enable_real_run: 'Enable global switch',
        blocked: 'Gate blocked',
        real_run: 'Dispatch real',
      },
      nextActionHints: {
        add_target: 'Add a Bilibili video or dynamic activity URL first. Homepages and test URLs cannot be probed or executed.',
        review_rule: 'Expand the rule plan in the activity pool, verify the original rule text, and confirm required actions.',
        add_account: 'Add and calibrate a Bilibili account on the Accounts page first.',
        configure_adapter: 'Save adapter selectors from a complete probe on the Ops page first.',
        review_risk: 'Review recent account risk on the Safety page first.',
        enable_real_run: 'The global real-run switch requires admin confirmation on the Ops page.',
        blocked: 'The real-run gate is not satisfied yet.',
      },
      realGateBlockers: {
        invalid_lottery_target: 'Target URL is not actionable',
        lottery_action_plan_required: 'Action plan missing',
        lottery_rule_review_required: 'Activity rule needs review',
        lottery_required_actions_missing: 'No required actions found',
        no_calibrated_ready_account: 'No calibrated account',
        real_adapter_not_enabled: 'Adapter disabled',
        global_real_run_disabled: 'Global switch off',
        recent_complete_probe_required: 'Recent full probe missing',
        recent_shadow_run_required: 'Recent shadow missing',
        recent_account_risk_event: 'Recent account risk',
      },
      strategyReasons: {
        active_run_in_progress: 'Active run in progress',
        no_safe_account: 'No safe account',
        circuit_breaker_open: 'Circuit breaker open',
        dry_validation_needed: 'Dry-run validation needed',
        shadow_validation_needed: 'Shadow-run validation needed',
        real_gate_ready: 'Real gate ready',
        adapter_not_ready: 'Adapter not ready',
        probe_not_ready: 'Probe not ready',
        real_run_disabled: 'Real-run disabled',
        real_gate_not_ready: 'Real gate not ready',
        recent_platform_risk: 'Recent platform risk',
        recent_failures: 'Recent failures',
        high_value: 'High value',
        platform_knowledge_used: 'Platform knowledge used',
        low_knowledge_confidence: 'Low knowledge confidence',
        historical_win_rate_used: 'Historical win rate used',
        account_reputation_used: 'Account reputation used',
        account_reputation_low: 'Low account reputation',
      },
    },
    strategy: {
      eyebrow: 'Decision runtime',
      title: 'Strategy console',
      subtitle: 'Strategy queue grouped by priority tier; every recommendation can be expanded into its score breakdown. Recommendations only — real-run still requires manual confirmation.',
      totalTargets: 'Candidates',
      actNow: 'Act now',
      strong: 'Strong',
      holding: 'On hold',
      rank: 'Rank',
      target: 'Target',
      score: 'Score',
      expectedValue: 'Expected value',
      mode: 'Suggested mode',
      reasons: 'Reasons',
      action: 'Action',
      explain: 'Explain',
      emptyTier: 'No targets in this tier',
      explainTitle: 'Decision explanation',
      explaining: 'Building explanation…',
      modeDecision: 'Mode decision',
      scoreBreakdown: 'Score breakdown',
      modeMultiplier: 'Mode multiplier',
      total: 'Total',
      winProbability: 'Win probability estimate',
      baseline: 'Baseline',
      observedRate: 'Observed win rate',
      confidenceWeight: 'Confidence weight',
      blended: 'Blended',
      trustScore: 'Trust score',
      accountTrust: 'Account trust',
      confidenceBonus: 'Confidence bonus',
      riskPenalty: 'Risk penalty',
      trustTotal: 'Trust score',
      knowledgeConfidence: 'Knowledge confidence',
      safetyNote: 'The strategy layer only suggests mode and ranking; it never bypasses the real-run gate. Real execution requires admin confirmation.',
      tier: { S: 'Act now (S)', A: 'Strong candidates (A)', B: 'Low priority / validation (B)', hold: 'On hold / blocked' },
      components: {
        base_value: 'Base value',
        validation_bonus: 'Validation bonus',
        knowledge_bonus: 'Knowledge bonus',
        account_bonus: 'Account bonus',
        expected_value_bonus: 'Expected value bonus',
        probability_bonus: 'Probability bonus',
        risk_penalty: 'Risk penalty',
      },
      knowledgeParts: {
        lottery_sample: 'Lottery sample',
        result_labels: 'Result labels',
        task_runs: 'Task runs',
        shadow_success: 'Shadow success',
        real_success: 'Real success',
      },
      units: { targets: 'targets', tierS: 'tier S', tierA: 'tier A', hold: 'on hold' },
    },
    knowledge: {
      eyebrow: 'Knowledge runtime',
      title: 'Knowledge base',
      subtitle: 'Data maturity, platform and account profiles, and the learning-gap checklist, built from the last 30 days of events, targets, runs, and risk records.',
      maturity: 'Data maturity',
      events: 'Events',
      resultLabels: 'Result labels',
      shadowSuccess: 'Shadow success',
      platformProfiles: 'Platform profiles',
      accountProfiles: 'Account profiles',
      learningGaps: 'Learning gaps',
      platform: 'Platform',
      confidence: 'Confidence',
      lotteries: 'Lotteries',
      winRate: 'Win rate',
      runs: 'Runs',
      successRate: 'Success rate',
      shadowReal: 'Shadow / Real',
      risk: 'Risk',
      account: 'Account',
      reputation: 'Reputation',
      noData: 'No platform data yet',
      noAccounts: 'No account profiles yet',
      noGaps: 'No learning gaps',
      levels: { learning_ready: 'Learning-ready', usable: 'Usable', warming: 'Warming', cold_start: 'Cold start' },
      units: { events: 'events', labels: 'labels', runs: 'runs' },
    },
    risk: {
      eyebrow: 'Safety',
      title: 'Risk events',
      proxyPool: 'Proxy pool',
      activeExits: 'Active exits',
      coolingExits: 'Cooling exits',
      assigned: 'Assigned',
      proxyExits: 'Proxy exits',
      proxyUrl: 'Proxy URL',
      type: 'Type',
      provider: 'Provider',
      region: 'Region',
      addProxy: 'Add proxy',
      proxy: 'Proxy',
      status: 'Status',
      health: 'Health',
      cooldown: 'Cooldown',
      account: 'Account',
      action: 'Action',
      unassigned: 'Unassigned',
      cool30m: 'Cool 30m',
      active: 'Active',
      dead: 'Dead',
      noProxies: 'No proxy exits configured',
      time: 'Time',
      detail: 'Detail',
      noEvents: 'No risk events',
      added: 'Proxy added',
      cooled: 'Proxy P{id} moved to cooldown',
      statusSet: 'Proxy P{id} marked {status}',
      check: 'Check',
      lastCheck: 'Last check',
      checkOk: 'Proxy P{id} check passed in {latency}ms',
      checkFailed: 'Proxy P{id} check failed: {error}',
      units: {
        exits: 'exits',
        usable: 'usable',
        cooldown: 'cooldown',
        accounts: 'accounts',
      },
    },
    tasks: {
      eyebrow: 'Stream',
      title: 'Realtime task events',
      connected: 'Connected',
      connecting: 'Connecting',
      disconnected: 'Disconnected',
      waiting: 'Waiting for events',
      streamReady: 'Realtime event stream connected',
      streamDisconnected: 'Realtime event stream disconnected; the browser will retry automatically',
      badPayload: 'Received an invalid realtime event',
      task: 'Task',
      account: 'Account',
      phase: 'Phase',
    },
    events: {
      eyebrow: 'Runtime memory',
      title: 'Event timeline',
      filters: 'Filters',
      latest: 'Latest events',
      aggregate: 'Aggregate',
      eventType: 'Event type',
      correlation: 'Correlation ID',
      actor: 'Actor',
      service: 'Service',
      payload: 'Payload',
      time: 'Time',
      allAggregates: 'All aggregates',
      clearFilters: 'Clear filters',
      loading: 'Loading',
      noEvents: 'No events',
      aggregates: {
        account: 'Account',
        lottery: 'Lottery',
        task: 'Task',
        risk: 'Risk',
        browser: 'Browser',
        worker: 'Worker',
        notification_channel: 'Notification channel',
        notification_log: 'Notification log',
        platform: 'Platform',
        source: 'Discovery source',
        lottery_import: 'Target import',
        system: 'System',
      },
    },
    deploy: {
      eyebrow: 'Ops',
      title: 'Operations & Notify',
      runtime: 'Runtime',
      currentVersion: 'Current version',
      globalBreaker: 'Global circuit breaker',
      workerReload: 'Worker reload',
      reloadArmed: 'Confirm reload signal',
      runtimeRollback: 'Runtime emergency rollback',
      rollbackHint: 'Disable real-run, open the global circuit breaker, cancel queued real-run tasks, and notify Worker reload.',
      rollbackReason: 'Rollback reason',
      rollbackArmed: 'Confirm runtime rollback',
      applyRollback: 'Apply rollback',
      rollbackDone: 'Runtime rollback applied; {count} queued real-run task(s) cancelled.',
      uploadPackage: 'Upload package',
      hmacSignature: 'HMAC signature',
      notificationTest: 'Notification test',
      channel: 'Channel',
      testTitle: 'Title',
      content: 'Content',
      sendTest: 'Send test',
      missingSelected: 'Selected channel is missing secrets. Configure it below before sending a test.',
      notificationHealth: 'Notification health',
      configured: 'Configured',
      missingSecrets: 'Missing secrets',
      last: 'Last',
      sent: 'sent',
      failed: 'failed',
      noLogs: 'No logs',
      healthy: 'Healthy',
      needsCheck: 'Needs check',
      notSet: 'Not set',
      configuredChannels: 'Configured channels: {count}. Account risk, login calibration, task results, and manual tests share this dispatch path.',
      lastDispatchSkip: 'Last dispatch skip: {title}',
      notificationGuide: 'Notification configuration guide',
      missing: 'Missing',
      testEndpoint: 'Test endpoint: {endpoint}. Secrets are never echoed back by the API.',
      envBundle: 'Notification .env bundle',
      productionReady: 'At least one notification channel is configured for production alerts.',
      productionMissing: 'No usable notification channel is configured; production alerts will be logged but not delivered externally.',
      missingRequired: 'Missing variables',
      minimumEnv: 'Minimum viable config',
      fullEnv: 'All channel config',
      none: 'None',
      saveSecret: 'Save secret',
      clearSecret: 'Clear secret',
      secretSaved: '{channel} secret saved',
      secretCleared: '{channel} secret cleared',
      secretRequired: 'Enter at least one secret field',
      secretConfigured: 'Configured; enter a new value to replace it',
      secretBundle: 'Paste notification .env bundle',
      secretBundlePlaceholder: 'Paste one or more lines, for example:\nSERVERCHAN_KEY=...\nFEISHU_WEBHOOK=https://...\nGENERIC_WEBHOOK_URL=https://...\nTELEGRAM_BOT_TOKEN=...\nTELEGRAM_CHAT_ID=...',
      saveSecretBundle: 'Save secret bundle',
      useMinimumEnv: 'Use minimum template',
      secretBundleRequired: 'Paste at least one notification secret',
      secretBundleSaved: 'Notification secrets saved: {keys}',
      secretPlaceholder: 'Paste secret or webhook URL',
      adapterBuilder: 'Adapter configuration builder',
      selectorJson: 'Selector JSON',
      generateBase64: 'Generate Base64',
      saveRuntimeSelectors: 'Save runtime',
      clearRuntimeSelectors: 'Clear runtime',
      resetSample: 'Reset sample',
      envOutput: '.env output',
      envPlaceholder: 'Generate Base64 after confirming selectors from probe evidence.',
      preferredKey: 'Preferred key: {key}. All four phases must be present before real actions are enabled.',
      probeCandidates: 'Probe selector candidates',
      probe: 'Probe',
      platform: 'Platform',
      activity: 'Activity',
      visiblePhases: 'Visible phases',
      action: 'Action',
      useDraft: 'Use draft',
      noProbeCandidates: 'No usable probe selector result yet. Run a probe after logging in with a low-risk account.',
      notificationLogs: 'Notification logs',
      result: 'Result',
      created: 'Created',
      noNotificationLogs: 'No notification logs',
      reloadSent: 'Worker reload signal sent',
      operationFailed: 'Operation failed',
      uploadReady: 'Enter the HMAC signature, then choose an update package to upload.',
      uploadDone: 'Update package uploaded',
      uploadFailed: 'Upload failed',
      notificationQueued: 'Notification queued: N{logId}',
      selectorEncoded: 'Adapter selector config encoded. Put the generated line into .env, then rebuild services.',
      selectorSaved: 'Saved runtime selector config for {count} platform(s)',
      selectorCleared: '{platform} runtime selectors cleared',
      invalidSelector: 'Invalid selector JSON: {message}',
      draftLoaded: 'Selector draft loaded from probe {probe}. Review it before generating Base64.',
      loadFailed: 'Operations data failed to load: {message}',
      planned: 'Planned',
      realRunReadiness: '{platform} real-run readiness',
      realRunReadinessHint: 'Check account, probe, selectors, shadow-run, and the global switch before real execution.',
      readyForReal: 'Ready for real-run',
      needsAction: 'Needs action',
      ready: 'Ready',
      loadProbeDraft: 'Load probe draft',
      workflowTarget: 'Current target',
      currentSafeAction: 'Current safe step',
      workflowState: 'Execution state',
      workflowIdle: 'Waiting',
      noTargetForPlatform: 'No {platform} target',
      invalidTargetsIgnored: 'Homepage or test URLs were ignored. Add an actionable target in Lottery Tasks.',
      noProbeDraft: 'No complete probe draft is available',
      probeInProgress: 'Probe {id} in progress',
      shadowInProgress: 'Shadow {id} in progress',
      probeRunning: 'Probe running',
      shadowRunning: 'Shadow running',
      workflowSubmitting: 'Submitting',
      runSafeNextStep: 'Run: {action}',
      reviewRealRunTask: 'Review real-run',
      reviewRealRunSwitchButton: 'Review Real-run switch',
      workflowQueued: '{action} queued as {id}',
      reviewRealRunSwitch: 'Safety evidence is complete. Review and manually confirm the Real-run switch above.',
      realRunReadyNotice: 'The real-run gate is ready. Open Lottery Tasks to choose the target and account, then confirm execution.',
      workflowManualReview: 'This step requires manual review. Follow the gate guidance before continuing.',
      readinessSteps: {
        targetTitle: 'Actionable target',
        targetDetail: 'Use a target URL validated by the platform (video, dynamic post, Weibo status, or note). The homepage or profile pages are not execution targets.',
        accountTitle: 'Safe account',
        accountDetail: 'At least one calibrated {platform} account with valid credentials is required.',
        probeTitle: 'Complete probe',
        probeDetail: 'Follow, like, comment, and repost probe phases must complete within 24 hours.',
        selectorTitle: 'Runtime selectors',
        selectorDetail: 'Save adapter selectors for this platform from reviewed probe evidence.',
        shadowTitle: 'Shadow-run evidence',
        shadowDetail: 'Validate the page and login state in no-side-effect mode before real execution.',
        globalTitle: 'Global switch',
        globalDetail: 'The real-run switch stays off by default and requires admin confirmation after evidence is ready.',
      },
    },
    experiments: {
      eyebrow: 'Decision runtime',
      title: 'Experiment runtime',
      subtitle: 'Compares dry-run / shadow-run strategy branches only. Results are advisory; risk signals auto-stop affected branches, and real execution still goes through the real-run gate.',
      totalExperiments: 'Experiments',
      running: 'Running',
      stopped: 'Stopped',
      experimentList: 'Experiment list',
      id: 'Experiment ID',
      name: 'Name',
      platform: 'Platform',
      mode: 'Mode',
      status: 'Status',
      branches: 'Branches',
      action: 'Action',
      details: 'Details',
      noExperiments: 'No experiments yet',
      detailTitle: 'Experiment detail',
      loadingDetail: 'Loading detail…',
      overview: 'Overview',
      hypothesis: 'Hypothesis',
      stoppedReason: 'Stopped reason',
      stopExperiment: 'Stop experiment',
      guardrailsTitle: 'Safety guardrails',
      noGuardrails: 'No guardrails reported',
      comparison: 'Branch comparison',
      comparisonStatus: 'Comparison status',
      comparisonStatuses: {
        insufficient_data: 'Insufficient data',
        leader_found: 'Leader found',
      },
      leader: 'Leader',
      minSamples: 'Min samples',
      branchStats: 'Branch stats',
      branchKey: 'Branch',
      runs: 'Runs',
      winRate: 'Win rate',
      participationRate: 'Participation rate',
      failureRate: 'Failure rate',
      riskRate: 'Risk rate',
      stopSignal: 'Stop signal',
      ok: 'OK',
      stopBranch: 'Stop branch',
      noBranches: 'No branch data',
      safetyNote: 'The experiment layer only suggests comparisons; it never auto-dispatches or bypasses the real-run gate. Stop actions require admin/operator confirmation.',
      stopReasonPrompt: 'Enter a stop reason',
      branchStopped: 'Branch {branch} stopped',
      experimentStopped: 'Experiment stopped',
      units: { experiments: 'experiments' },
      guardrails: {
        captcha_or_ratelimit_stops_branch: 'Captcha or rate-limit signals auto-stop the affected branch',
        results_are_advisory_only: 'Results are advisory only',
        runs_in_dry_or_shadow_only: 'Runs in dry-run / shadow-run only',
        real_run_requires_admin_and_evidence_gate: 'Real-run experiments still require admin confirmation and the evidence gate',
        comment_content_from_controlled_template_pool: 'Comment content is drawn from a controlled template pool',
      },
      stopReasons: {
        hard_risk_signal: 'Hard risk signal (captcha/ban)',
        risk_rate_exceeded: 'Risk rate exceeded threshold',
      },
    },
    riskIntel: {
      eyebrow: 'Risk intelligence',
      title: 'Risk intelligence forecast',
      subtitle: '24-hour account risk forecasts are advisory and only ever tighten dispatch; they never relax the real-run gate.',
      forecastTable: 'Account risk forecast',
      account: 'Account',
      platform: 'Platform',
      status: 'Status',
      reputation: 'Reputation',
      riskScore: 'Risk score',
      forecast24h: '24h forecast',
      forecastBand: 'Forecast band',
      recommendedAction: 'Recommended action',
      reasons: 'Reasons',
      noData: 'No risk intelligence data yet',
      units: { accounts: 'accounts' },
      bands: {
        high: 'High',
        elevated: 'Elevated',
        moderate: 'Moderate',
        low: 'Low',
      },
      actions: {
        allow: 'Allow',
        dry_run_only: 'Dry-run only',
        cooldown: 'Cooldown',
        relogin: 'Re-login required',
        manual_review: 'Manual review',
        block: 'Block',
      },
      reasonCodes: {
        hard_risk_signal_24h: 'Hard risk signal in the last 24h',
        account_locked_state: 'Account frozen or banned',
        login_required_state: 'Account requires login',
        cooling_state: 'Account is cooling down',
        calibration_not_succeeded: 'Latest calibration did not succeed',
        daily_volume_high: 'Daily task volume is high',
        recent_risk_events: 'Recent risk events',
        consecutive_failures: 'High consecutive failures',
        low_reputation: 'Low account reputation',
      },
    },
    learning: {
      eyebrow: 'Learning runtime',
      title: 'Learning & predictions',
      subtitle: 'Transparent linear model producing an advisory success probability. Predictions are advisory only and never relax the real-run gate.',
      modelCard: 'Model card',
      modelVersion: 'Model version',
      featureSetVersion: 'Feature set version',
      modelType: 'Model type',
      bias: 'Bias',
      feature: 'Feature',
      weight: 'Weight',
      description: 'Description',
      noModel: 'No model data yet',
      loadingModel: 'Loading model…',
      predictions: 'Target predictions',
      lottery: 'Lottery',
      platform: 'Platform',
      valueScore: 'Value score',
      probability: 'Probability',
      confidenceBand: 'Confidence band',
      topDrivers: 'Top drivers',
      noPredictions: 'No predictions yet',
      safetyNote: 'Predictions are advisory probabilities and not an execution basis; real execution still requires the real-run gate and manual confirmation.',
      bands: {
        high: 'High',
        moderate: 'Moderate',
        low: 'Low',
        very_low: 'Very low',
      },
      features: {
        value: 'Target value',
        win_rate: 'Historical win rate',
        knowledge_confidence: 'Knowledge confidence',
        account_reputation: 'Account reputation',
        validation_depth: 'Validation depth',
        recent_risk: 'Recent risk',
      },
    },
    governance: {
      eyebrow: 'Governance runtime',
      title: 'Governance & gate policy',
      subtitle: 'The real-run gate as a versioned, replayable policy. Evaluation is read-only — it never dispatches anything and never relaxes the gate, and is fail-closed by default.',
      activePolicy: 'Active policy',
      policyKey: 'Policy key',
      policyVersion: 'Version',
      required: 'Required',
      remediation: 'Remediation',
      yes: 'Yes',
      no: 'No',
      noGates: 'No gates defined',
      loadingPolicy: 'Loading policy…',
      policyVersions: 'Policy versions',
      note: 'Note',
      active: 'Active',
      createdAt: 'Created',
      noVersions: 'No policy versions yet',
      evaluateGate: 'Evaluate real-run gate',
      evaluateHint: 'Enter a lottery ID to evaluate its real-run gate. Evaluation records a replayable decision.',
      lotteryIdPlaceholder: 'Lottery ID',
      evaluate: 'Evaluate',
      evaluating: 'Evaluating…',
      invalidLotteryId: 'Enter a valid lottery ID',
      outcome: 'Outcome',
      decisionId: 'Decision ID',
      gateChecklist: 'Gate checklist',
      failedReasons: 'Failed reasons',
      nextAction: 'Next action',
      recentDecisions: 'Recent decisions',
      subject: 'Subject',
      action: 'Action',
      replay: 'Replay',
      noDecisions: 'No decisions yet',
      replayMatch: 'Replay matches',
      replayMismatch: 'Replay mismatch',
      versionMatch: 'Policy version matches',
      versionMismatch: 'Policy version differs',
      gateCode: 'Gate',
      outcomes: {
        allow: 'Allow',
        block: 'Block',
      },
      gates: {
        global_real_run_enabled: { label: 'Global real-run enabled', remediation: 'Enable the global switch' },
        circuit_breaker_closed: { label: 'Circuit breaker closed', remediation: 'Review the circuit breaker' },
        valid_lottery_target: { label: 'Valid lottery target', remediation: 'Add a valid target' },
        action_plan_reviewed: { label: 'Action plan reviewed', remediation: 'Review the activity rule' },
        calibrated_account_available: { label: 'Calibrated account available', remediation: 'Add an account' },
        real_adapter_enabled: { label: 'Real adapter enabled', remediation: 'Configure the adapter' },
        recent_complete_probe: { label: 'Recent complete probe', remediation: 'Run a probe' },
        recent_shadow_run: { label: 'Recent shadow run', remediation: 'Run a shadow-run' },
        no_recent_account_risk: { label: 'No recent account risk', remediation: 'Review account risk' },
      },
      remediations: {
        enable_real_run: 'Enable the global real-run switch',
        review_breaker: 'Review the circuit breaker state',
        add_target: 'Add a valid activity target',
        review_rule: 'Review the activity rule and action plan',
        add_account: 'Add and calibrate an account',
        configure_adapter: 'Configure the real action adapter',
        probe: 'Run an adapter probe',
        shadow_run: 'Run a shadow-run',
        review_risk: 'Review account risk',
        real_run: 'Ready to dispatch real-run',
      },
    },
    transitions: {
      eyebrow: 'Transition runtime',
      title: 'Policy transition graph',
      subtitle: 'Every policy version change leaves an immutable transition record: why it changed, what changed, how to roll it back, and whether it tightened or loosened the gate. Publishing a new version never changes live behaviour — only Activate does.',
      safetyBanner: 'Publishing is not activating: only clicking Activate changes which policy version the real-run gate actually evaluates against. Any change that loosens a gate requires a written justification and is flagged for extra review.',
      activeVersion: 'Active version',
      chainTitle: 'Version lineage',
      noChain: 'No transitions recorded yet; the current version is the built-in default.',
      active: 'Active',
      activated: 'Activated',
      pendingActivation: 'Published, not yet active',
      activate: 'Activate',
      activating: 'Activating…',
      classification: 'Classification',
      classifications: {
        tightening: 'Tightening',
        loosening: 'Loosening',
        neutral: 'Neutral',
      },
      extraReview: 'Needs extra review',
      viewDiff: 'View diff',
      hideDiff: 'Hide diff',
      addedGates: 'Added gates',
      removedGates: 'Removed gates',
      changedGates: 'Required flag changed',
      noGateChanges: 'No related changes',
      required: 'required',
      optional: 'optional',
      impactScope: 'Impact scope',
      rollbackCondition: 'Rollback condition',
      loosJustification: 'Loosening justification',
      publishTitle: 'Propose a new policy version',
      publishHint: 'Edit the JSON below to draft a new version, then fill in the reason and rollback condition. Submitting only records and publishes the version — it never activates automatically.',
      definitionLabel: 'Policy definition (JSON)',
      seedFromActive: 'Start from active policy',
      reasonCodeLabel: 'Reason code',
      rollbackLabel: 'Rollback condition',
      rollbackPlaceholder: 'e.g. revert to the previous version if the false-positive rate exceeds 5%',
      loosJustificationLabel: 'Loosening justification (required if this loosens any gate)',
      noteLabel: 'Note',
      publish: 'Publish version',
      publishing: 'Publishing…',
      publishResult: 'Publish result',
      invalidJson: 'Policy definition must be valid JSON',
      rollbackRequired: 'Rollback condition is required',
      publishSuccess: 'Policy version published (not yet active)',
      activateSuccess: 'Policy version activated',
      reasons: {
        experiment_result: 'Experiment result',
        risk_tightening: 'Risk tightening',
        manual_review: 'Manual review',
        incident_response: 'Incident response',
        scheduled_review: 'Scheduled review',
      },
    },
    status: {
      ready: 'Ready',
      gray: 'Gray',
      login_required: 'Login needed',
      warming: 'Checking',
      cooling: 'Cooling',
      frozen: 'Frozen',
      executing: 'Executing',
      pending: 'Pending',
      claimed: 'Claimed',
      running: 'Running',
      participated: 'Joined',
      won: 'Won',
      lost: 'Lost',
      succeeded: 'Succeeded',
      failed: 'Failed',
      queued: 'Queued',
      opening: 'Opening',
      waiting_scan: 'Scan QR',
      scanned: 'Scanned, confirm on phone',
      confirmed: 'Confirmed',
      expired: 'Expired',
      banned: 'Banned',
      unknown: 'Unknown',
      draft: 'Draft',
      stopped: 'Stopped',
      completed: 'Completed',
    },
  },
};

export function UiProvider({ children }) {
  const [language, setLanguageState] = useState(() => localStorage.getItem('dpms_language') || 'zh');
  const [theme, setThemeState] = useState(() => localStorage.getItem('dpms_theme') || 'system');
  const [toasts, setToasts] = useState([]);

  useEffect(() => {
    const media = window.matchMedia('(prefers-color-scheme: dark)');
    const applyTheme = () => {
      const resolved = theme === 'system' ? (media.matches ? 'dark' : 'light') : theme;
      document.documentElement.dataset.themeMode = theme;
      document.documentElement.dataset.theme = resolved;
    };
    applyTheme();
    media.addEventListener('change', applyTheme);
    return () => media.removeEventListener('change', applyTheme);
  }, [theme]);

  const setLanguage = useCallback((next) => {
    setLanguageState(next);
    localStorage.setItem('dpms_language', next);
  }, []);

  const setTheme = useCallback((next) => {
    setThemeState(next);
    localStorage.setItem('dpms_theme', next);
  }, []);

  const notify = useCallback((message, type = 'info') => {
    const id = `${Date.now()}-${Math.random()}`;
    setToasts(prev => [...prev, { id, message, type }]);
    window.setTimeout(() => {
      setToasts(prev => prev.filter(item => item.id !== id));
    }, 3600);
  }, []);

  const t = useCallback((path) => {
    const parts = path.split('.');
    let current = dictionaries[language] || dictionaries.zh;
    for (const part of parts) current = current?.[part];
    return current || path;
  }, [language]);

  const value = useMemo(
    () => ({ language, setLanguage, theme, setTheme, toasts, notify, t }),
    [language, notify, setLanguage, setTheme, t, theme, toasts],
  );

  return <UiContext.Provider value={value}>{children}</UiContext.Provider>;
}

export function useUi() {
  const context = useContext(UiContext);
  if (!context) throw new Error('useUi must be used inside UiProvider');
  return context;
}
