import { createContext, useCallback, useContext, useEffect, useMemo, useState } from 'react';

const UiContext = createContext(null);

const dictionaries = {
  zh: {
    nav: {
      dashboard: '总览',
      accounts: '账号登录',
      lotteries: '任务编排',
      tasks: '实时流',
      events: '事件时间线',
      risk: '安全风控',
      deploy: '运维通知',
    },
    common: {
      local: '本机运行',
      language: '语言',
      theme: '主题',
      light: '浅色',
      dark: '深色',
      system: '跟随系统',
      refresh: '刷新',
      delete: '删除',
      cancel: '取消',
    },
    accounts: {
      eyebrow: '账号访问',
      title: '登录控制中心',
      healthRecheck: '健康复查',
      qrLogin: '二维码登录',
      qrBroker: '扫码登录代理',
      platform: '平台',
      generateQr: '生成二维码',
      qrOpening: '正在打开平台登录页并截取二维码画面...',
      qrEmpty: '选择平台后生成二维码登录会话，然后使用官方 App 扫码。',
      cookieLogin: 'Cookie 登录',
      cookieImport: '导入原始 Cookie 或 JSON Cookie',
      cookie: 'Cookie',
      cookiePlaceholder: '直接粘贴 Cookie 请求头，例如：SESSDATA=...; bili_jct=...; DedeUserID=...',
      importCreate: '导入并创建',
      accountPool: '账号池',
      refreshCredentials: '刷新已有账号凭据',
      noAccounts: '暂无账号',
      noRefresh: '请先创建账号，再刷新凭据。',
      imported: '已导入',
      missing: '缺失',
      notChecked: '未检查',
      evidence: '证据',
      noRisk: '暂无近期风险',
      accountCreated: '账号已创建',
      importQueued: '账号已创建并进入校准队列',
      credentialSaved: 'Cookie 已保存并进入校准队列',
      statusUpdated: '账号状态已更新',
      calibrationQueued: '账号校准已排队',
      healthDone: '账号健康复查完成',
      deleteConfirm: '确认删除该账号及关联记录？此操作不可撤销。',
      deleted: '账号已删除',
      rawCookieHint: '支持直接粘贴浏览器 Cookie 请求头、多行 Cookie 或 JSON Cookie 导出。',
      runtime: '运行状态',
    },
    dashboard: {
      eyebrow: '运行时',
      title: '运维总览',
      workersOnline: '在线 Worker',
      pendingTasks: '待处理任务',
      readyAccounts: '可用账号',
      coolingAccounts: '冷却账号',
      todayExecutions: '今日执行',
      memory: '内存',
      dryRunPlatforms: 'Dry-run 平台',
      realRunPlatforms: 'Real-run 平台',
      safeAccounts: '安全账号',
      notifyChannels: '通知通道',
      proxyExits: '代理出口',
      risk24h: '24 小时风险',
      nextActions: '下一步动作',
      noActions: '当前无需修复动作',
      strategyAdvice: '复盘与策略建议',
      strategyWindow: '基于最近 {days} 天执行、风险、目标池与通知状态生成。',
      noStrategyAdvice: '当前暂无策略建议',
      productionReady: '生产就绪',
      productionGate: '生产门禁',
      blocked: '阻塞',
      platformReadiness: '平台就绪度',
      platform: '平台',
      dryRun: 'Dry run',
      realRun: 'Real run',
      probe: '探针',
      blockers: '阻塞项',
      noProbe: '无探针',
      clear: '通过',
      loading: '正在加载就绪度数据',
      kickerLogin: '登录',
      kickerSafety: '安全',
      kickerNotify: '通知',
      loginTitle: '二维码 + Cookie 会话',
      loginText: '账号只有在存在有效加密凭据后才会进入账号池。',
      safetyTitle: '频率窗口 + 每日上限',
      safetyText: 'Worker 会阻止不安全执行，并将风险账号移入冷却或需登录状态。',
      notifyTitle: 'ServerChan / 飞书 / Webhook / Telegram',
      notifyText: '每次分发都会记录日志，避免通知失败被静默隐藏。',
      blockersMap: {
        'adapter probe is incomplete': '适配器探针不完整',
        'no calibrated ready account': '没有已校准可用账号',
        'real adapter not enabled': '真实动作适配器未启用',
        'global real-run switch is disabled': '全局 real-run 开关关闭',
        adapter_probe_incomplete: '适配器探针不完整',
        no_calibrated_ready_account: '没有已校准可用账号',
        real_adapter_not_enabled: '真实动作适配器未启用',
        global_real_run_disabled: '全局 real-run 开关关闭',
      },
      actionsMap: {
        configureNotificationTitle: '配置至少一个通知通道',
        configureNotificationDetail: '设置 ServerChan、飞书、Webhook 或 Telegram 密钥后，发送一次通知测试。',
        reviewRiskTitle: '复查近期账号风险信号',
        reviewRiskDetail: '进入安全风控页查看最新风险事件，必要时重新校准受影响账号。',
        addProxyTitle: '为生产账号添加隔离代理出口',
        addProxyDetail: '为每个生产账号绑定可用代理出口，并让高风险出口保持冷却。',
        addAccountTitle: '为 {platform} 添加已校准安全账号',
        addAccountDetail: '使用二维码或 Cookie 导入账号，然后运行账号校准，使 dry-run 可以安全自动选号。',
        completeProbeTitle: '完成 {platform} 适配器探针',
        completeProbeDetail: '用低风险账号运行探针，确认关注、点赞、评论、转发四个阶段可见。',
        enableAdapterTitle: '启用 {platform} 真实动作适配器',
        enableAdapterDetail: '基于探针证据配置选择器，真实执行前必须覆盖四个阶段。',
        dryRunOnlyTitle: '生产派发保持 dry-run 模式',
        dryRunOnlyDetail: '可以继续 dry-run 验证；真实执行必须等账号、探针、适配器和门禁全部满足。',
      },
      checksMap: {
        worker_onlineTitle: '至少一个 Worker 在线',
        worker_onlineDetail: '必须能看到 Worker 消费者或数据库心跳，否则任务不会执行。',
        real_run_global_switchTitle: '全局 real-run 开关受控',
        real_run_global_switchDetail: '真实执行默认关闭，只有完成生产确认后才应打开。',
        notification_readyTitle: '至少一个通知通道可用',
        notification_readyDetail: '生产告警需要 ServerChan、飞书、Webhook 或 Telegram。',
        target_pool_readyTitle: '存在可派发抽奖目标',
        target_pool_readyDetail: '目标池至少需要一个 pending 或 claimed 状态的目标。',
        all_platforms_dry_readyTitle: '所有平台具备 dry-run 账号',
        all_platforms_dry_readyDetail: '多平台 dry-run 需要每个平台至少一个已校准账号。',
        real_run_availableTitle: '至少一个平台可真实执行',
        real_run_availableDetail: '真实执行需要账号、探针证据、适配器和全局门禁同时满足。',
        active_proxy_exitTitle: '存在可用代理出口',
        active_proxy_exitDetail: '账号隔离需要至少一个未冷却的 active 代理出口。',
        safe_accounts_proxiedTitle: '可用账号已分配代理',
        safe_accounts_proxiedDetail: '生产账号应绑定可用代理出口，降低账号关联风险。',
        recent_risk_clearTitle: '24 小时内无账号风险',
        recent_risk_clearDetail: '近期风险事件需要复核，必要时重新校准账号。',
      },
      strategyMap: {
        configure_notificationsTitle: '先配置通知再进入自主运行',
        configure_notificationsDetail: '当前没有外部通知通道，中奖、失败、验证码或封禁可能只留在日志中。',
        run_shadow_before_realTitle: '真实执行前先跑 shadow-run',
        run_shadow_before_realDetail: '目标池已有待处理目标，但最近 7 天没有成功 shadow-run 记录。',
        promote_dry_to_shadowTitle: '将 dry-run 验证推进到 shadow-run',
        promote_dry_to_shadowDetail: 'dry-run 已经成功，下一步应在无副作用模式下打开真实页面验证登录态和风险信号。',
        complete_real_gateTitle: '基于 shadow 证据完成 real-run 门禁',
        complete_real_gateDetail: '已有 shadow-run 证据，但当前没有平台满足真实执行就绪条件。',
        review_failed_runsTitle: '放量前复查失败执行',
        review_failed_runsDetail: '近期任务失败需要结合证据截图和事件时间线复盘，再扩大调度规模。',
        cooldown_risky_accountsTitle: '冷却并重新校准风险账号',
        cooldown_risky_accountsDetail: '近期存在风险事件，建议冷却受影响账号、重新校准，或绑定更安全代理出口。',
        prioritize_high_value_targetsTitle: '优先处理高价值待派发目标',
        prioritize_high_value_targetsDetail: '存在高评分待处理目标且有安全账号可用，shadow-run 通过后应优先按预期价值派发。',
        recover_stale_tasksTitle: '恢复超时活跃任务',
        recover_stale_tasksDetail: '发现超过 30 分钟仍处于 queued/running 的任务，需要检查 Worker 健康和恢复守护逻辑。',
        continue_controlled_real_runTitle: '保持受控 real-run 节奏',
        continue_controlled_real_runDetail: '近期真实执行成功，策略复盘未发现紧急阻塞项。',
      },
      units: {
        nodes: '节点',
        items: '项',
        accounts: '账号',
        runs: '次',
        configured: '已配置',
        calibrated: '已校准',
        events: '事件',
        of: '/',
      },
    },
    lotteries: {
      eyebrow: '工作流',
      title: '任务编排',
      autoPick: '自动选择已校准账号',
      calibrated: '已校准',
      strategyQueue: '策略队列',
      strategyQueueHint: '根据目标价值、账号就绪、dry/shadow 证据、风险和失败记录排序。',
      rank: '排名',
      priorityScore: '策略分',
      expectedValue: '期望值',
      recommendedMode: '建议模式',
      recommendedAccount: '推荐账号',
      knowledge: '经验',
      reasons: '原因',
      dispatchRecommended: '按建议派发',
      noStrategyTargets: '暂无可排程目标',
      dryRun: 'Dry run',
      shadowRun: 'Shadow run',
      real: 'Real',
      dry_run: 'Dry run',
      shadow_run: 'Shadow run',
      real_run: 'Real',
      blocked: '阻塞',
      qrLogin: '二维码登录',
      cookieLogin: 'Cookie 登录',
      realActions: '真实动作',
      adapter: '适配器',
      safeAccounts: '安全账号',
      phases: '阶段',
      adapterLoading: '正在加载适配器诊断',
      cookieDomain: 'Cookie 域名',
      manualIntake: '手动活动录入',
      platform: '平台',
      activityUrl: '活动 URL',
      score: '评分',
      create: '创建',
      discoverySources: '发现源',
      type: '类型',
      interval: '间隔',
      sourceValue: '源内容',
      saveSource: '保存源',
      scanNow: '立即扫描',
      sourceSaved: '发现源已保存',
      scanComplete: '扫描完成：新增 {inserted}，发现 {found}，失败 {failed}',
      activityCreated: '活动已创建',
      defaultPlatform: '默认平台',
      defaultScore: '默认评分',
      uploadTargets: '上传目标',
      targetList: '目标列表',
      targetPlaceholder: '每行一个 URL，或使用 platform,url,score,expires_at\nhttps://www.bilibili.com/\nbilibili,https://t.bilibili.com/123,80,2026-06-30 23:59:59',
      importTargets: '导入目标',
      targetsImported: '目标导入完成：新增 {created_count}，重复 {duplicate_count}，无效 {invalid_count}',
      targetFileLoaded: '已读取目标文件：{name}',
      importSummary: '已处理 {received} 行，新增 {created_count}，重复 {duplicate_count}，无效 {invalid_count}',
      dispatchQueued: '任务已派发',
      probeQueued: '适配器探针已排队',
      resultUpdated: '结果已更新',
      activityPool: '活动池',
      url: 'URL',
      status: '状态',
      expires: '过期时间',
      action: '操作',
      noSafeAccount: '无安全账号',
      adapterPending: '适配器待配置',
      dispatchReal: '派发真实任务',
      dispatchDry: '派发 Dry',
      dispatch_dry_run: '派发 Dry',
      dispatch_shadow_run: '派发 Shadow',
      dispatch_real_run: '派发真实任务',
      won: '中奖',
      lost: '未中',
      probe: '探针',
      noActivities: '暂无活动',
      noSources: '暂无发现源',
      adapterProbes: '适配器探针',
      account: '账号',
      activity: '活动',
      visiblePhases: '可见阶段',
      quality: '质量',
      evidence: '证据',
      raw: '原始',
      openProbe: '打开探针',
      noAdapterProbes: '暂无适配器探针',
      executionRuns: '执行记录',
      task: '任务',
      mode: '模式',
      openEvidence: '打开证据',
      noRuns: '暂无执行记录',
      lastScan: '上次扫描',
      active: '启用',
      realAdapterMissing: '该平台真实动作适配器尚未可用。',
      realGate: 'Real 门禁',
      gateReady: '可真实执行',
      gateBlocked: '证据不足',
      gateUnknown: '未计算',
      nextActions: {
        add_account: '先添加账号',
        configure_adapter: '先配置适配器',
        probe: '先跑探针',
        shadow_run: '先跑 Shadow',
        review_risk: '先复查风险',
        enable_real_run: '先开启总开关',
        blocked: '门禁阻断',
        real_run: '派发真实任务',
      },
      nextActionHints: {
        add_account: '请先到账号登录页添加并校准 Bilibili 账号。',
        configure_adapter: '请先到运维通知页，根据完整探针保存适配器选择器。',
        review_risk: '请先到安全风控页复查账号近期风险。',
        enable_real_run: '全局 real-run 开关需要管理员在运维页确认开启。',
        blocked: 'Real-run 门禁尚未满足。',
      },
      realGateBlockers: {
        no_calibrated_ready_account: '无校准账号',
        real_adapter_not_enabled: '适配器未启用',
        global_real_run_disabled: '总开关关闭',
        recent_complete_probe_required: '缺近期完整探针',
        recent_shadow_run_required: '缺近期 Shadow',
        recent_account_risk_event: '账号近期有风险',
      },
      strategyReasons: {
        active_run_in_progress: '已有运行中任务',
        no_safe_account: '无安全账号',
        circuit_breaker_open: '熔断器开启',
        dry_validation_needed: '需要 dry-run 验证',
        shadow_validation_needed: '需要 shadow-run 验证',
        real_gate_ready: '真实执行门禁已满足',
        adapter_not_ready: '适配器未就绪',
        probe_not_ready: '探针未就绪',
        real_run_disabled: 'real-run 关闭',
        real_gate_not_ready: '真实执行门禁未满足',
        recent_platform_risk: '近期平台风险',
        recent_failures: '近期失败',
        high_value: '高价值目标',
        platform_knowledge_used: '已使用平台经验',
        low_knowledge_confidence: '经验置信度偏低',
        historical_win_rate_used: '已使用历史中奖率',
        account_reputation_used: '已使用账号信誉',
        account_reputation_low: '账号信誉偏低',
      },
    },
    risk: {
      eyebrow: '安全',
      title: '风险事件',
      proxyPool: '代理池',
      activeExits: '可用出口',
      coolingExits: '冷却出口',
      assigned: '已分配',
      proxyExits: '代理出口',
      proxyUrl: '代理 URL',
      type: '类型',
      provider: '服务商',
      region: '地区',
      addProxy: '添加代理',
      proxy: '代理',
      status: '状态',
      health: '健康度',
      cooldown: '冷却',
      account: '账号',
      action: '操作',
      unassigned: '未分配',
      cool30m: '冷却 30 分钟',
      active: '启用',
      dead: '失效',
      noProxies: '暂无代理出口',
      time: '时间',
      detail: '详情',
      noEvents: '暂无风险事件',
      added: '代理已添加',
      cooled: '代理 P{id} 已进入冷却',
      statusSet: '代理 P{id} 已标记为 {status}',
      check: '检测',
      lastCheck: '最后检测',
      checkOk: '代理 P{id} 检测通过，延迟 {latency}ms',
      checkFailed: '代理 P{id} 检测失败：{error}',
      units: {
        exits: '出口',
        usable: '可用',
        cooldown: '冷却',
        accounts: '账号',
      },
    },
    tasks: {
      eyebrow: '实时流',
      title: '实时任务事件',
      connected: '已连接',
      connecting: '连接中',
      disconnected: '已断开',
      waiting: '等待事件',
      streamReady: '实时事件流已连接',
      streamDisconnected: '实时事件流已断开，浏览器将自动重试',
      badPayload: '收到无法解析的实时事件',
      task: '任务',
      account: '账号',
      phase: '阶段',
    },
    events: {
      eyebrow: '运行时记忆',
      title: '事件时间线',
      filters: '筛选',
      latest: '最新事件',
      aggregate: '聚合',
      eventType: '事件类型',
      correlation: '关联 ID',
      actor: '操作者',
      service: '服务',
      payload: '载荷',
      time: '时间',
      allAggregates: '全部聚合',
      clearFilters: '清空筛选',
      loading: '加载中',
      noEvents: '暂无事件',
      aggregates: {
        account: '账号',
        lottery: '抽奖',
        task: '任务',
        risk: '风险',
        browser: '浏览器',
        worker: 'Worker',
        notification_channel: '通知通道',
        notification_log: '通知日志',
        platform: '平台',
        source: '发现源',
        lottery_import: '目标导入',
        system: '系统',
      },
    },
    deploy: {
      eyebrow: '运维',
      title: '运维与通知',
      runtime: '运行时',
      currentVersion: '当前版本',
      globalBreaker: '全局熔断器',
      workerReload: '重载 Worker',
      reloadArmed: '确认发送重载信号',
      runtimeRollback: '运行态紧急回滚',
      rollbackHint: '关闭 real-run，打开全局熔断器，撤销排队中的真实任务，并通知 Worker 重新加载。',
      rollbackReason: '回滚原因',
      rollbackArmed: '确认执行运行态回滚',
      applyRollback: '执行回滚',
      rollbackDone: '运行态回滚已执行，已撤销 {count} 个排队 real-run。',
      uploadPackage: '上传更新包',
      hmacSignature: 'HMAC 签名',
      notificationTest: '通知测试',
      channel: '通道',
      testTitle: '标题',
      content: '内容',
      sendTest: '发送测试',
      missingSelected: '当前通道缺少密钥。请在下方补齐配置后再发送测试。',
      notificationHealth: '通知健康',
      configured: '已配置',
      missingSecrets: '缺少密钥',
      last: '上次',
      sent: '已发送',
      failed: '失败',
      noLogs: '无日志',
      healthy: '健康',
      needsCheck: '需检查',
      notSet: '未设置',
      configuredChannels: '已配置通知通道：{count}。账号风险、登录校准、任务结果和手动测试共用该分发路径。',
      lastDispatchSkip: '上次跳过分发：{title}',
      notificationGuide: '通知配置说明',
      missing: '缺失',
      testEndpoint: '测试接口：{endpoint}。API 不会回显密钥。',
      envBundle: '通知 .env 配置包',
      productionReady: '至少一个通知通道已可用，可承接生产告警。',
      productionMissing: '尚未配置可用通知通道，生产告警会被记录但不会外发。',
      missingRequired: '缺失变量',
      minimumEnv: '最小可用配置',
      fullEnv: '全部通道配置',
      none: '无',
      saveSecret: '保存密钥',
      clearSecret: '清空密钥',
      secretSaved: '{channel} 密钥已保存',
      secretCleared: '{channel} 密钥已清空',
      secretRequired: '请至少填写一个密钥字段',
      secretConfigured: '已配置，输入新值可覆盖',
      secretPlaceholder: '粘贴密钥或 Webhook URL',
      secretBundle: '批量粘贴通知 .env',
      secretBundlePlaceholder: '支持粘贴多行，例如：\nSERVERCHAN_KEY=...\nFEISHU_WEBHOOK=https://...\nGENERIC_WEBHOOK_URL=https://...\nTELEGRAM_BOT_TOKEN=...\nTELEGRAM_CHAT_ID=...',
      saveSecretBundle: '批量保存密钥',
      useMinimumEnv: '使用最小模板',
      secretBundleRequired: '请粘贴至少一个通知密钥',
      secretBundleSaved: '通知密钥已保存：{keys}',      adapterBuilder: '适配器配置构建器',
      selectorJson: '选择器 JSON',
      generateBase64: '生成 Base64',
      saveRuntimeSelectors: '保存到运行时',
      clearRuntimeSelectors: '清空运行时',
      resetSample: '重置示例',
      envOutput: '.env 输出',
      envPlaceholder: '确认探针证据中的选择器后生成 Base64。',
      preferredKey: '推荐键：{key}。真实动作启用前必须覆盖全部四个阶段。',
      probeCandidates: '探针选择器候选',
      probe: '探针',
      platform: '平台',
      activity: '活动',
      visiblePhases: '可见阶段',
      action: '操作',
      useDraft: '使用草稿',
      noProbeCandidates: '暂无可用探针选择器结果。请先使用低风险账号登录并运行探针。',
      notificationLogs: '通知日志',
      result: '结果',
      created: '创建时间',
      noNotificationLogs: '暂无通知日志',
      reloadSent: 'Worker 重载信号已发送',
      operationFailed: '操作失败',
      uploadReady: '填写 HMAC 签名后选择更新包上传。',
      uploadDone: '更新包已上传',
      uploadFailed: '上传失败',
      notificationQueued: '通知已排队：N{logId}',
      selectorEncoded: '适配器选择器配置已编码。请将生成的配置行写入 .env 后重建服务。',
      selectorSaved: '已保存 {count} 个平台的运行时选择器配置',
      selectorCleared: '{platform} 运行时选择器已清空',
      invalidSelector: '选择器 JSON 无效：{message}',
      draftLoaded: '已从探针 {probe} 载入选择器草稿。生成 Base64 前请复核。',
      loadFailed: '运维数据加载失败：{message}',
      planned: '计划中',
    },
    status: {
      ready: '可用',
      gray: '灰度',
      login_required: '需登录',
      warming: '校验中',
      cooling: '冷却中',
      frozen: '冻结',
      executing: '执行中',
      pending: '待处理',
      claimed: '已领取',
      running: '运行中',
      participated: '已参与',
      won: '中奖',
      lost: '未中',
      succeeded: '成功',
      failed: '失败',
      queued: '排队中',
      opening: '打开中',
      waiting_scan: '等待扫码',
      confirmed: '已确认',
      expired: '已过期',
      banned: '封禁',
      unknown: '未知',
    },
  },
  en: {
    nav: {
      dashboard: 'Overview',
      accounts: 'Accounts',
      lotteries: 'Tasks',
      tasks: 'Live stream',
      events: 'Event timeline',
      risk: 'Safety',
      deploy: 'Operations',
    },
    common: {
      local: 'Local runtime',
      language: 'Language',
      theme: 'Theme',
      light: 'Light',
      dark: 'Dark',
      system: 'System',
      refresh: 'Refresh',
      delete: 'Delete',
      cancel: 'Cancel',
    },
    accounts: {
      eyebrow: 'Account access',
      title: 'Login control center',
      healthRecheck: 'Health recheck',
      qrLogin: 'QR login',
      qrBroker: 'Scan-to-login broker',
      platform: 'Platform',
      generateQr: 'Generate QR',
      qrOpening: 'Opening the platform login page and capturing the QR screen...',
      qrEmpty: 'Choose a platform, generate a QR login session, then scan it with the official app.',
      cookieLogin: 'Cookie login',
      cookieImport: 'Import raw Cookie or JSON Cookie',
      cookie: 'Cookie',
      cookiePlaceholder: 'Paste a Cookie header directly, for example: SESSDATA=...; bili_jct=...; DedeUserID=...',
      importCreate: 'Import and create',
      accountPool: 'Account pool',
      refreshCredentials: 'Refresh existing credentials',
      noAccounts: 'No accounts yet',
      noRefresh: 'Create an account before refreshing credentials.',
      imported: 'Imported',
      missing: 'Missing',
      notChecked: 'Not checked',
      evidence: 'Evidence',
      noRisk: 'No recent risk',
      accountCreated: 'Account created',
      importQueued: 'Account created and queued for calibration',
      credentialSaved: 'Cookie saved and queued for calibration',
      statusUpdated: 'Account status updated',
      calibrationQueued: 'Account calibration queued',
      healthDone: 'Account health recheck completed',
      deleteConfirm: 'Delete this account and its related records? This cannot be undone.',
      deleted: 'Account deleted',
      rawCookieHint: 'Raw browser Cookie headers, multiline Cookie text, and JSON Cookie exports are supported.',
      runtime: 'Runtime',
    },
    dashboard: {
      eyebrow: 'Runtime',
      title: 'Operations overview',
      workersOnline: 'Workers online',
      pendingTasks: 'Pending tasks',
      readyAccounts: 'Ready accounts',
      coolingAccounts: 'Cooling accounts',
      todayExecutions: 'Today executions',
      memory: 'Memory',
      dryRunPlatforms: 'Dry-run platforms',
      realRunPlatforms: 'Real-run platforms',
      safeAccounts: 'Safe accounts',
      notifyChannels: 'Notify channels',
      proxyExits: 'Proxy exits',
      risk24h: 'Risk 24h',
      nextActions: 'Next actions',
      noActions: 'No remediation actions are currently required',
      strategyAdvice: 'Review & strategy advice',
      strategyWindow: 'Generated from executions, risk, target pool, and notification state over the last {days} days.',
      noStrategyAdvice: 'No strategy advice right now',
      productionReady: 'Production ready',
      productionGate: 'Production gate',
      blocked: 'Blocked',
      platformReadiness: 'Platform readiness',
      platform: 'Platform',
      dryRun: 'Dry run',
      realRun: 'Real run',
      probe: 'Probe',
      blockers: 'Blockers',
      noProbe: 'No probe',
      clear: 'Clear',
      loading: 'Readiness data is loading',
      kickerLogin: 'Login',
      kickerSafety: 'Safety',
      kickerNotify: 'Notify',
      loginTitle: 'QR + Cookie session',
      loginText: 'Accounts enter the pool only after a valid encrypted credential is available.',
      safetyTitle: 'Rate window + daily cap',
      safetyText: 'Worker blocks unsafe runs and moves risky accounts to cooling or login-required states.',
      notifyTitle: 'ServerChan / Feishu / Webhook / Telegram',
      notifyText: 'Each delivery is logged so silent notification failure does not hide task results.',
      blockersMap: {
        'adapter probe is incomplete': 'adapter probe is incomplete',
        'no calibrated ready account': 'no calibrated ready account',
        'real adapter not enabled': 'real adapter not enabled',
        'global real-run switch is disabled': 'global real-run switch is disabled',
        adapter_probe_incomplete: 'adapter probe is incomplete',
        no_calibrated_ready_account: 'no calibrated ready account',
        real_adapter_not_enabled: 'real adapter not enabled',
        global_real_run_disabled: 'global real-run switch is disabled',
      },
      actionsMap: {
        configureNotificationTitle: 'Configure at least one notification channel',
        configureNotificationDetail: 'Set SERVERCHAN_KEY, FEISHU_WEBHOOK, GENERIC_WEBHOOK_URL, or TELEGRAM_BOT_TOKEN plus TELEGRAM_CHAT_ID, then send a notification test.',
        reviewRiskTitle: 'Review recent account risk signals',
        reviewRiskDetail: 'Open Safety, inspect the latest risk events, and recalibrate any affected account before returning it to the ready pool.',
        addProxyTitle: 'Add isolated proxy exits for production accounts',
        addProxyDetail: 'Open Safety, add one proxy exit per account, and keep risky exits in cooldown before enabling higher-volume multi-platform automation.',
        addAccountTitle: 'Add a calibrated safe account for {platform}',
        addAccountDetail: 'Use QR login or cookie import, then run account calibration so dry-run dispatch can safely auto-pick the account.',
        completeProbeTitle: 'Complete adapter probe for {platform}',
        completeProbeDetail: 'Probe a low-risk real lottery page until follow, like, comment, and repost phases are visible; then review the recommended selector config.',
        enableAdapterTitle: 'Enable real action adapter for {platform}',
        enableAdapterDetail: 'After a safe account is calibrated, configure selectors verified by adapter probe evidence.',
        dryRunOnlyTitle: 'Keep production dispatch in dry-run mode',
        dryRunOnlyDetail: 'Dry-run validation can continue, but real execution should remain gated until accounts, probe evidence, adapters, and safety checks pass.',
      },
      checksMap: {
        worker_onlineTitle: 'At least one worker is online',
        worker_onlineDetail: 'A visible worker consumer or DB heartbeat is required before tasks can execute.',
        real_run_global_switchTitle: 'Global real-run switch is controlled',
        real_run_global_switchDetail: 'Real execution is disabled by default and should be enabled only after production approval.',
        notification_readyTitle: 'At least one notification channel is available',
        notification_readyDetail: 'Production alerts need ServerChan, Feishu, Webhook, or Telegram delivery.',
        target_pool_readyTitle: 'Dispatchable lottery targets exist',
        target_pool_readyDetail: 'The target pool needs at least one pending or claimed target.',
        all_platforms_dry_readyTitle: 'All platforms have dry-run accounts',
        all_platforms_dry_readyDetail: 'Multi-platform dry-run requires at least one calibrated ready account per platform.',
        real_run_availableTitle: 'At least one platform can run real actions',
        real_run_availableDetail: 'Real execution requires accounts, probe evidence, adapters, and the global gate together.',
        active_proxy_exitTitle: 'An active proxy exit is available',
        active_proxy_exitDetail: 'Account isolation needs at least one active proxy exit outside cooldown.',
        safe_accounts_proxiedTitle: 'Ready accounts have proxy exits',
        safe_accounts_proxiedDetail: 'Production accounts should bind usable proxy exits to reduce account linkage risk.',
        recent_risk_clearTitle: 'No account risk in the last 24 hours',
        recent_risk_clearDetail: 'Recent risk events need review and possibly account recalibration.',
      },
      strategyMap: {
        configure_notificationsTitle: 'Configure notification before autonomous runs',
        configure_notificationsDetail: 'No external notification channel is configured, so wins, failures, captcha, or bans may only be visible in logs.',
        run_shadow_before_realTitle: 'Run shadow-run before real-run',
        run_shadow_before_realDetail: 'Pending targets exist, but no successful shadow-run was recorded in the last 7 days.',
        promote_dry_to_shadowTitle: 'Promote dry-run validation into shadow-run',
        promote_dry_to_shadowDetail: 'Dry-run is succeeding, so the next safe step is opening real pages with no side effects to validate login state and risk signals.',
        complete_real_gateTitle: 'Complete the real-run gate after shadow evidence',
        complete_real_gateDetail: 'Shadow-run evidence exists, but no platform currently satisfies real-run readiness.',
        review_failed_runsTitle: 'Review failed runs before increasing volume',
        review_failed_runsDetail: 'Recent task failures should be inspected through evidence screenshots and event timeline before scaling the scheduler.',
        cooldown_risky_accountsTitle: 'Cooldown and recalibrate risky accounts',
        cooldown_risky_accountsDetail: 'Risk events were recorded recently; affected accounts should be cooled, recalibrated, or assigned safer proxy exits.',
        prioritize_high_value_targetsTitle: 'Prioritize high-value pending targets',
        prioritize_high_value_targetsDetail: 'High-score pending targets exist and safe accounts are available; dispatch order should favor expected value after shadow-run clears.',
        recover_stale_tasksTitle: 'Recover stale active tasks',
        recover_stale_tasksDetail: 'Queued or running tasks older than 30 minutes were found; inspect Worker health and recovery daemon behavior.',
        continue_controlled_real_runTitle: 'Continue controlled real-run cadence',
        continue_controlled_real_runDetail: 'Recent real-run tasks succeeded and no urgent blocker was detected by the strategy review.',
      },
      units: {
        nodes: 'nodes',
        items: 'items',
        accounts: 'accounts',
        runs: 'runs',
        configured: 'configured',
        calibrated: 'calibrated',
        events: 'events',
        of: 'of',
      },
    },
    lotteries: {
      eyebrow: 'Workflow',
      title: 'Task orchestration',
      autoPick: 'Auto-pick calibrated account',
      calibrated: 'calibrated',
      strategyQueue: 'Strategy queue',
      strategyQueueHint: 'Ranked by target value, account readiness, dry/shadow evidence, risk, and failed runs.',
      rank: 'Rank',
      priorityScore: 'Strategy score',
      expectedValue: 'Expected value',
      recommendedMode: 'Recommended mode',
      recommendedAccount: 'Recommended account',
      knowledge: 'Knowledge',
      reasons: 'Reasons',
      dispatchRecommended: 'Dispatch suggested',
      noStrategyTargets: 'No schedulable targets',
      dryRun: 'Dry run',
      shadowRun: 'Shadow run',
      real: 'Real',
      dry_run: 'Dry run',
      shadow_run: 'Shadow run',
      real_run: 'Real',
      blocked: 'Blocked',
      qrLogin: 'QR login',
      cookieLogin: 'Cookie login',
      realActions: 'Real actions',
      adapter: 'Adapter',
      safeAccounts: 'Safe accounts',
      phases: 'Phases',
      adapterLoading: 'Adapter diagnostics loading',
      cookieDomain: 'Cookie domain',
      manualIntake: 'Manual activity intake',
      platform: 'Platform',
      activityUrl: 'Activity URL',
      score: 'Score',
      create: 'Create',
      discoverySources: 'Discovery sources',
      type: 'Type',
      interval: 'Interval',
      sourceValue: 'Source value',
      saveSource: 'Save source',
      scanNow: 'Scan now',
      sourceSaved: 'Discovery source saved',
      scanComplete: 'Scan complete: {inserted} inserted, {found} found, {failed} failed',
      activityCreated: 'Activity created',
      defaultPlatform: 'Default platform',
      defaultScore: 'Default score',
      uploadTargets: 'Upload targets',
      targetList: 'Target list',
      targetPlaceholder: 'One URL per line, or platform,url,score,expires_at\nhttps://www.bilibili.com/\nbilibili,https://t.bilibili.com/123,80,2026-06-30 23:59:59',
      importTargets: 'Import targets',
      targetsImported: 'Targets imported: {created_count} created, {duplicate_count} duplicates, {invalid_count} invalid',
      targetFileLoaded: 'Target file loaded: {name}',
      importSummary: 'Processed {received} lines, {created_count} created, {duplicate_count} duplicates, {invalid_count} invalid',
      dispatchQueued: 'Task dispatched',
      probeQueued: 'Adapter probe queued',
      resultUpdated: 'Result updated',
      activityPool: 'Activity pool',
      url: 'URL',
      status: 'Status',
      expires: 'Expires',
      action: 'Action',
      noSafeAccount: 'No safe account',
      adapterPending: 'Adapter pending',
      dispatchReal: 'Dispatch real',
      dispatchDry: 'Dispatch dry',
      dispatch_dry_run: 'Dispatch dry',
      dispatch_shadow_run: 'Dispatch shadow',
      dispatch_real_run: 'Dispatch real',
      won: 'Won',
      lost: 'Lost',
      probe: 'Probe',
      noActivities: 'No activities',
      noSources: 'No discovery sources',
      adapterProbes: 'Adapter probes',
      account: 'Account',
      activity: 'Activity',
      visiblePhases: 'Visible phases',
      quality: 'Quality',
      evidence: 'Evidence',
      raw: 'Raw',
      openProbe: 'Open probe',
      noAdapterProbes: 'No adapter probes',
      executionRuns: 'Execution runs',
      task: 'Task',
      mode: 'Mode',
      openEvidence: 'Open evidence',
      noRuns: 'No runs',
      lastScan: 'Last scan',
      active: 'Active',
      realAdapterMissing: 'Real adapter is not available for this platform yet.',
      realGate: 'Real gate',
      gateReady: 'Ready',
      gateBlocked: 'Evidence missing',
      gateUnknown: 'Unknown',
      nextActions: {
        add_account: 'Add account first',
        configure_adapter: 'Configure adapter',
        probe: 'Run probe first',
        shadow_run: 'Run shadow first',
        review_risk: 'Review risk first',
        enable_real_run: 'Enable global switch',
        blocked: 'Gate blocked',
        real_run: 'Dispatch real',
      },
      nextActionHints: {
        add_account: 'Add and calibrate a Bilibili account on the Accounts page first.',
        configure_adapter: 'Save adapter selectors from a complete probe on the Ops page first.',
        review_risk: 'Review recent account risk on the Safety page first.',
        enable_real_run: 'The global real-run switch requires admin confirmation on the Ops page.',
        blocked: 'The real-run gate is not satisfied yet.',
      },
      realGateBlockers: {
        no_calibrated_ready_account: 'No calibrated account',
        real_adapter_not_enabled: 'Adapter disabled',
        global_real_run_disabled: 'Global switch off',
        recent_complete_probe_required: 'Recent full probe missing',
        recent_shadow_run_required: 'Recent shadow missing',
        recent_account_risk_event: 'Recent account risk',
      },
      strategyReasons: {
        active_run_in_progress: 'Active run in progress',
        no_safe_account: 'No safe account',
        circuit_breaker_open: 'Circuit breaker open',
        dry_validation_needed: 'Dry-run validation needed',
        shadow_validation_needed: 'Shadow-run validation needed',
        real_gate_ready: 'Real gate ready',
        adapter_not_ready: 'Adapter not ready',
        probe_not_ready: 'Probe not ready',
        real_run_disabled: 'Real-run disabled',
        real_gate_not_ready: 'Real gate not ready',
        recent_platform_risk: 'Recent platform risk',
        recent_failures: 'Recent failures',
        high_value: 'High value',
        platform_knowledge_used: 'Platform knowledge used',
        low_knowledge_confidence: 'Low knowledge confidence',
        historical_win_rate_used: 'Historical win rate used',
        account_reputation_used: 'Account reputation used',
        account_reputation_low: 'Low account reputation',
      },
    },
    risk: {
      eyebrow: 'Safety',
      title: 'Risk events',
      proxyPool: 'Proxy pool',
      activeExits: 'Active exits',
      coolingExits: 'Cooling exits',
      assigned: 'Assigned',
      proxyExits: 'Proxy exits',
      proxyUrl: 'Proxy URL',
      type: 'Type',
      provider: 'Provider',
      region: 'Region',
      addProxy: 'Add proxy',
      proxy: 'Proxy',
      status: 'Status',
      health: 'Health',
      cooldown: 'Cooldown',
      account: 'Account',
      action: 'Action',
      unassigned: 'Unassigned',
      cool30m: 'Cool 30m',
      active: 'Active',
      dead: 'Dead',
      noProxies: 'No proxy exits configured',
      time: 'Time',
      detail: 'Detail',
      noEvents: 'No risk events',
      added: 'Proxy added',
      cooled: 'Proxy P{id} moved to cooldown',
      statusSet: 'Proxy P{id} marked {status}',
      check: 'Check',
      lastCheck: 'Last check',
      checkOk: 'Proxy P{id} check passed in {latency}ms',
      checkFailed: 'Proxy P{id} check failed: {error}',
      units: {
        exits: 'exits',
        usable: 'usable',
        cooldown: 'cooldown',
        accounts: 'accounts',
      },
    },
    tasks: {
      eyebrow: 'Stream',
      title: 'Realtime task events',
      connected: 'Connected',
      connecting: 'Connecting',
      disconnected: 'Disconnected',
      waiting: 'Waiting for events',
      streamReady: 'Realtime event stream connected',
      streamDisconnected: 'Realtime event stream disconnected; the browser will retry automatically',
      badPayload: 'Received an invalid realtime event',
      task: 'Task',
      account: 'Account',
      phase: 'Phase',
    },
    events: {
      eyebrow: 'Runtime memory',
      title: 'Event timeline',
      filters: 'Filters',
      latest: 'Latest events',
      aggregate: 'Aggregate',
      eventType: 'Event type',
      correlation: 'Correlation ID',
      actor: 'Actor',
      service: 'Service',
      payload: 'Payload',
      time: 'Time',
      allAggregates: 'All aggregates',
      clearFilters: 'Clear filters',
      loading: 'Loading',
      noEvents: 'No events',
      aggregates: {
        account: 'Account',
        lottery: 'Lottery',
        task: 'Task',
        risk: 'Risk',
        browser: 'Browser',
        worker: 'Worker',
        notification_channel: 'Notification channel',
        notification_log: 'Notification log',
        platform: 'Platform',
        source: 'Discovery source',
        lottery_import: 'Target import',
        system: 'System',
      },
    },
    deploy: {
      eyebrow: 'Ops',
      title: 'Operations & Notify',
      runtime: 'Runtime',
      currentVersion: 'Current version',
      globalBreaker: 'Global circuit breaker',
      workerReload: 'Worker reload',
      reloadArmed: 'Confirm reload signal',
      runtimeRollback: 'Runtime emergency rollback',
      rollbackHint: 'Disable real-run, open the global circuit breaker, cancel queued real-run tasks, and notify Worker reload.',
      rollbackReason: 'Rollback reason',
      rollbackArmed: 'Confirm runtime rollback',
      applyRollback: 'Apply rollback',
      rollbackDone: 'Runtime rollback applied; {count} queued real-run task(s) cancelled.',
      uploadPackage: 'Upload package',
      hmacSignature: 'HMAC signature',
      notificationTest: 'Notification test',
      channel: 'Channel',
      testTitle: 'Title',
      content: 'Content',
      sendTest: 'Send test',
      missingSelected: 'Selected channel is missing secrets. Configure it below before sending a test.',
      notificationHealth: 'Notification health',
      configured: 'Configured',
      missingSecrets: 'Missing secrets',
      last: 'Last',
      sent: 'sent',
      failed: 'failed',
      noLogs: 'No logs',
      healthy: 'Healthy',
      needsCheck: 'Needs check',
      notSet: 'Not set',
      configuredChannels: 'Configured channels: {count}. Account risk, login calibration, task results, and manual tests share this dispatch path.',
      lastDispatchSkip: 'Last dispatch skip: {title}',
      notificationGuide: 'Notification configuration guide',
      missing: 'Missing',
      testEndpoint: 'Test endpoint: {endpoint}. Secrets are never echoed back by the API.',
      envBundle: 'Notification .env bundle',
      productionReady: 'At least one notification channel is configured for production alerts.',
      productionMissing: 'No usable notification channel is configured; production alerts will be logged but not delivered externally.',
      missingRequired: 'Missing variables',
      minimumEnv: 'Minimum viable config',
      fullEnv: 'All channel config',
      none: 'None',
      saveSecret: 'Save secret',
      clearSecret: 'Clear secret',
      secretSaved: '{channel} secret saved',
      secretCleared: '{channel} secret cleared',
      secretRequired: 'Enter at least one secret field',
      secretConfigured: 'Configured; enter a new value to replace it',
      secretBundle: 'Paste notification .env bundle',
      secretBundlePlaceholder: 'Paste one or more lines, for example:\nSERVERCHAN_KEY=...\nFEISHU_WEBHOOK=https://...\nGENERIC_WEBHOOK_URL=https://...\nTELEGRAM_BOT_TOKEN=...\nTELEGRAM_CHAT_ID=...',
      saveSecretBundle: 'Save secret bundle',
      useMinimumEnv: 'Use minimum template',
      secretBundleRequired: 'Paste at least one notification secret',
      secretBundleSaved: 'Notification secrets saved: {keys}',      secretPlaceholder: 'Paste secret or webhook URL',
      adapterBuilder: 'Adapter configuration builder',
      selectorJson: 'Selector JSON',
      generateBase64: 'Generate Base64',
      saveRuntimeSelectors: 'Save runtime',
      clearRuntimeSelectors: 'Clear runtime',
      resetSample: 'Reset sample',
      envOutput: '.env output',
      envPlaceholder: 'Generate Base64 after confirming selectors from probe evidence.',
      preferredKey: 'Preferred key: {key}. All four phases must be present before real actions are enabled.',
      probeCandidates: 'Probe selector candidates',
      probe: 'Probe',
      platform: 'Platform',
      activity: 'Activity',
      visiblePhases: 'Visible phases',
      action: 'Action',
      useDraft: 'Use draft',
      noProbeCandidates: 'No usable probe selector result yet. Run a probe after logging in with a low-risk account.',
      notificationLogs: 'Notification logs',
      result: 'Result',
      created: 'Created',
      noNotificationLogs: 'No notification logs',
      reloadSent: 'Worker reload signal sent',
      operationFailed: 'Operation failed',
      uploadReady: 'Enter the HMAC signature, then choose an update package to upload.',
      uploadDone: 'Update package uploaded',
      uploadFailed: 'Upload failed',
      notificationQueued: 'Notification queued: N{logId}',
      selectorEncoded: 'Adapter selector config encoded. Put the generated line into .env, then rebuild services.',
      selectorSaved: 'Saved runtime selector config for {count} platform(s)',
      selectorCleared: '{platform} runtime selectors cleared',
      invalidSelector: 'Invalid selector JSON: {message}',
      draftLoaded: 'Selector draft loaded from probe {probe}. Review it before generating Base64.',
      loadFailed: 'Operations data failed to load: {message}',
      planned: 'Planned',
    },
    status: {
      ready: 'Ready',
      gray: 'Gray',
      login_required: 'Login needed',
      warming: 'Checking',
      cooling: 'Cooling',
      frozen: 'Frozen',
      executing: 'Executing',
      pending: 'Pending',
      claimed: 'Claimed',
      running: 'Running',
      participated: 'Joined',
      won: 'Won',
      lost: 'Lost',
      succeeded: 'Succeeded',
      failed: 'Failed',
      queued: 'Queued',
      opening: 'Opening',
      waiting_scan: 'Scan QR',
      confirmed: 'Confirmed',
      expired: 'Expired',
      banned: 'Banned',
      unknown: 'Unknown',
    },
  },
};

export function UiProvider({ children }) {
  const [language, setLanguageState] = useState(() => localStorage.getItem('dpms_language') || 'zh');
  const [theme, setThemeState] = useState(() => localStorage.getItem('dpms_theme') || 'system');
  const [toasts, setToasts] = useState([]);

  useEffect(() => {
    const media = window.matchMedia('(prefers-color-scheme: dark)');
    const applyTheme = () => {
      const resolved = theme === 'system' ? (media.matches ? 'dark' : 'light') : theme;
      document.documentElement.dataset.themeMode = theme;
      document.documentElement.dataset.theme = resolved;
    };
    applyTheme();
    media.addEventListener('change', applyTheme);
    return () => media.removeEventListener('change', applyTheme);
  }, [theme]);

  const setLanguage = useCallback((next) => {
    setLanguageState(next);
    localStorage.setItem('dpms_language', next);
  }, []);

  const setTheme = useCallback((next) => {
    setThemeState(next);
    localStorage.setItem('dpms_theme', next);
  }, []);

  const notify = useCallback((message, type = 'info') => {
    const id = `${Date.now()}-${Math.random()}`;
    setToasts(prev => [...prev, { id, message, type }]);
    window.setTimeout(() => {
      setToasts(prev => prev.filter(item => item.id !== id));
    }, 3600);
  }, []);

  const t = useCallback((path) => {
    const parts = path.split('.');
    let current = dictionaries[language] || dictionaries.zh;
    for (const part of parts) current = current?.[part];
    return current || path;
  }, [language]);

  const value = useMemo(
    () => ({ language, setLanguage, theme, setTheme, toasts, notify, t }),
    [language, notify, setLanguage, setTheme, t, theme, toasts],
  );

  return <UiContext.Provider value={value}>{children}</UiContext.Provider>;
}

export function useUi() {
  const context = useContext(UiContext);
  if (!context) throw new Error('useUi must be used inside UiProvider');
  return context;
}
